#!/bin/bash

export ASAN_OPTIONS=detect_invalid_pointer_pairs=2

file="$1"
exe=$(mktemp)

trap 'rm -f "$exe"' EXIT

args=(
    -std=c++23
    -DLOCAL
    -fsanitize=address,undefined,leak
    # -fsanitize=pointer-compare,pointer-subtract
    # -fsanitize=bounds-strict
    # -fsanitize=float-divide-by-zero,float-cast-overflow
    # -fsanitize=nonnull-attribute,returns-nonnull-attribute
    # -fsanitize=bool,enum,vptr
    # -fsanitize=pointer-overflow,builtin
    -fno-omit-frame-pointer
    -Wall -Wextra -Wshadow
    -fmax-errors=1
    -O0
    -g
    -D_GLIBCXX_DEBUG
    -D_GLIBCXX_ASSERTIONS
)

inputs=()

for arg in "${@:2}"; do
    case "$arg" in
        -std=*)
            # Replace default -std
            for i in "${!args[@]}"; do
                [[ "${args[i]}" == -std=* ]] && args[i]="$arg"
            done
            ;;
        -D*)
            # Replace -DLOCAL if the same definition is customized
            name="${arg#-D}"
            name="${name%%=*}"

            replaced=false
            for i in "${!args[@]}"; do
                if [[ "${args[i]}" == -D"$name" || "${args[i]}" == -D"$name="* ]]; then
                    args[i]="$arg"
                    replaced=true
                    break
                fi
            done

            $replaced || args+=("$arg")
            ;;
        -*)
            args+=("$arg")
            ;;
        *)
            inputs+=("$arg")
            ;;
    esac
done

start=${EPOCHREALTIME/./}
g++ "${args[@]}" "$file" -o "$exe" || exit 1
end=${EPOCHREALTIME/./}
printf 'Compilation took %.6f seconds\n' "$((end - start))e-6"

if ((${#inputs[@]} == 0)); then
    "$exe"
else
    for input in "${inputs[@]}"; do
        printf '\n\033[1;34m===== %s =====\033[0m\n' "$input"
        "$exe" < "$input"
        echo
    done
fi
