import requests
import json
import os
import logging
from time import sleep
from bs4 import BeautifulSoup

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36",
}

EXTENSIONS = {
    "c++": "cpp",
    "clang": "cpp",
    "gcc": "c",
    "py": "py",
    "javascript": "js",
    "java": "java",
    "c#": "cs",
    "go": "go",
    "haskell": "hs",
    "kotlin": "kt",
    "delphi": "dpr",
    "pascal": "pas",
    "perl": "pl",
    "php": "php",
    "rust": "rs",
    "scala": "sc",
    "node": "js",
}

OUTPUT_DIR = "./atcoder/"

COMMENT_FORMATS = {
    "cpp": {"start": "/*", "line": " *", "end": " */"},
    "c": {"start": "/*", "line": " *", "end": " */"},
    "py": {"line": "#"},
    "js": {"start": "/*", "line": " *", "end": " */"},
    "java": {"start": "/*", "line": " *", "end": " */"},
    "cs": {"start": "/*", "line": " *", "end": " */"},
    "go": {"start": "/*", "line": " *", "end": " */"},
    "hs": {"line": "--"},
    "kt": {"start": "/*", "line": " *", "end": " */"},
    "dpr": {"line": "//"},
    "pas": {"start": "{", "line": "  ", "end": "}"},
    "pl": {"line": "#"},
    "php": {"start": "/*", "line": " *", "end": " */"},
    "rs": {"start": "/*", "line": " *", "end": " */"},
    "sc": {"start": "/*", "line": " *", "end": " */"},
    "txt": {"line": "#"},
}


def generate_header(solution, extension):
    fmt = COMMENT_FORMATS.get(extension, {"line": "#"})
    lines = []

    if "start" in fmt:
        lines.append(fmt["start"])
        lines.append(f"{fmt['line']} This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode")
        lines.append(f"{fmt['line']} Submission ID: {solution['solution_id']}")
        if solution.get("problem_name"):
            lines.append(f"{fmt['line']} Problem: {solution['problem_name']}")
        if solution.get("problem_link"):
            lines.append(f"{fmt['line']} Link: {solution['problem_link']}")
        lines.append(fmt["end"])
    else:
        prefix = fmt["line"]
        lines.append(f"{prefix} This file was auto-generated by UpCode")
        lines.append(f"{prefix} Submission ID: {solution['solution_id']}")
        if solution.get("problem_name"):
            lines.append(f"{prefix} Problem: {solution['problem_name']}")
        if solution.get("problem_link"):
            lines.append(f"{prefix} Link: {solution['problem_link']}")

    return "\n".join(lines)


def get_submission_info(username):
    cur = 0
    while True:
        submissions = json.loads(
            requests.get(
                f"https://kenkoooo.com/atcoder/atcoder-api/v3/user/submissions?user={username}&from_second={cur}"
            ).text
        )
        if not submissions:
            break

        for submission in submissions:
            if submission["result"] == "AC":
                try:
                    yield {
                        "language": submission["language"],
                        "problem_code": submission["problem_id"],
                        "solution_id": submission["id"],
                        "problem_link": f"https://atcoder.jp/contests/{submission['contest_id']}/tasks/{submission['problem_id']}",
                        "link": f"https://atcoder.jp/contests/{submission['contest_id']}/submissions/{submission['id']}",
                    }
                except KeyError:
                    pass

            cur = submission["epoch_second"] + 1

        sleep(1)


def get_code(html):
    soup = BeautifulSoup(html, "lxml")
    code_element = soup.select_one("#submission-code")
    if code_element:
        return code_element.text
    return ""


def get_solutions(username, all_info=None):
    if all_info is None:
        all_info = list(get_submission_info(username))[::-1]

    for info in all_info:
        try:
            response = requests.get(info["link"], headers=HEADERS)
            code = get_code(response.text)
            if code:
                yield {
                    "language": info["language"],
                    "problem_code": info["problem_code"],
                    "solution_id": info["solution_id"],
                    "problem_link": info["problem_link"],
                    "link": info["link"],
                    "solution": code,
                }
            sleep(0.5)
        except Exception as e:
            print(f"Error fetching Atcoder solution {info['solution_id']}: {e}")


def save_solution(solution):
    try:
        s = solution["language"].lower()

        extension = "txt"
        for key, value in EXTENSIONS.items():
            if key in s:
                extension = value
                break

        filename = (
            f"{solution['problem_code']} | {solution['problem_name']}.{extension}"
            if solution.get("problem_name", "")
            else f"{solution['problem_code']}.{extension}"
        )
        path = os.path.join(OUTPUT_DIR, filename)

        if os.path.exists(path):
            print(f"[Atcoder] Skipped {path} (Already exists, keeping the latest)")
            return True

        os.makedirs(os.path.dirname(path), exist_ok=True)

        solution_code = solution["solution"].replace("\r\n", "\n")
        header = generate_header(solution, extension)

        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(header + "\n\n")
            f.write(solution_code)

        print(f"[Atcoder] Successfully saved: {path}")
        print(f"  - Problem: {solution.get('problem_name', solution['problem_code'])}")
        print(f"  - Language: {solution['language']}")
        print(f"  - Solution ID: {solution['solution_id']}")
        return True

    except Exception as e:
        logging.error(f"{e} FOR {solution}")
        return False


def fetch_from_atcoder(atcoder_username):
    failed = []
    for solution in get_solutions(atcoder_username):
        if not save_solution(solution):
            failed.append(solution)

    for _ in range(3):
        if failed:
            sleep(180)
            new_failed = []
            for solution in get_solutions(atcoder_username, failed):
                if not save_solution(solution):
                    new_failed.append(solution)
            failed = new_failed


def main():
    fetch_from_atcoder("roychuang")


if __name__ == "__main__":
    main()
