/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75383575
 * Link: https://atcoder.jp/contests/abc157/tasks/abc157_f
 */

#include <cmath>
#include <cstdlib>
#include <functional>
#include <iostream>
#include <iomanip>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) std::cout << i << ' '; std::cout << std::endl; }
#define printlnv(x) { for (auto i : (x)) std::cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) std::begin(x), std::end(x)
#define rALL(x) std::rbegin(x), std::rend(x)
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

using DD = long double;

constexpr DD EPS = 1e-7;

struct Point {
        DD x, y;
        Point(DD _x, DD _y) : x(_x), y(_y) {};
        friend ostream& operator << (ostream &s, const Point &p) { return s << '(' << p.x << ", " << p.y << ')'; }
};

Point operator + (const Point &lhs, const Point &rhs) { return Point(lhs.x + rhs.x, lhs.y + rhs.y); }
Point operator - (const Point &lhs, const Point &rhs) { return Point(lhs.x - rhs.x, lhs.y - rhs.y); }
Point operator * (const DD &lhs, const Point &rhs) { return Point(lhs * rhs.x, lhs * rhs.y); }
Point operator * (const Point &lhs, const DD &rhs) { return Point(lhs.x * rhs, lhs.y * rhs); }
Point operator / (const Point &lhs, const DD &rhs) { return Point(lhs.x / rhs, lhs.y / rhs); }
Point complex_mul(const Point &lhs, const Point &rhs) { return Point(lhs.x * rhs.x - lhs.y * rhs.y, lhs.x * rhs.y + lhs.y * rhs.x); }
DD dot(const Point &lhs, const Point &rhs) { return lhs.x * rhs.x + lhs.y * rhs.y; }
DD det(const Point &lhs, const Point &rhs) { return lhs.x * rhs.y - lhs.y * rhs.x; }
DD abs(const Point &p) { return sqrt(SQ(p.x) + SQ(p.y)); }
bool eq(const Point &p, const Point &q) { return abs(p - q) < EPS; }

struct Circle : Point {
        DD r;
        Circle(DD x, DD y, DD r) : Point(x, y), r(r) {}
        Circle(Point p, DD r) : Point(p), r(r) {}
        friend ostream& operator << (ostream &s, const Circle &c) {return s << '(' << c.x << ", " << c.y << ", " << c.r << ')';}
};

vector<Point> circle_circle_intersect_points(const Circle &p, const Circle &q)  {
        DD d = abs(p - q);
        if (d < EPS) return {};
        if (d > p.r + q.r + EPS) return {};
        if (d < abs(p.r - q.r) - EPS) return {};
        DD rcos = (SQ(d) + SQ(p.r) - SQ(q.r)) / (2.0 * d), rsin;
        if (p.r - abs(rcos) < EPS) {
                rsin = 0;
        } else {
                rsin = sqrt(SQ(p.r) - SQ(rcos));
        }
        Point dir = (q - p) / d;
        Point p1 = p + complex_mul(dir, Point(rcos, rsin));
        Point p2 = p + complex_mul(dir, Point(rcos, -rsin));
        if (eq(p1, p2)) {
                return {p1};
        } else {
                return {p1, p2};
        }
}

void solution() {
        int N, K;
        cin >> N >> K;

        vector<DD> X(N), Y(N), C(N);
        for (int i = 0; i < N; i++) cin >> X[i] >> Y[i] >> C[i];

        const auto check = [&](DD t) -> bool {
                vector<Circle> cs(N, Circle(0, 0, -1));
                for (int i = 0; i < N; i++) {
                        cs[i] = Circle(X[i], Y[i], t / C[i]);
                }

                vector<Point> cand;
                for (int i = 0; i < N; i++) {
                        cand.push_back({X[i], Y[i]});
                        for (int j = i + 1; j < N; j++) {
                                auto isps = circle_circle_intersect_points(cs[i], cs[j]);
                                for (const auto &p : isps) cand.emplace_back(p);
                        }
                }

                for (const auto &p : cand) {
                        int cnt = 0;
                        for (int i = 0; i < N; i++) {
                                DD dist = abs(cs[i] - p);
                                if (dist < cs[i].r + EPS) cnt++;
                        }
                        if (cnt >= K) {
                                return true;
                        }
                }
                return false;
        };

        DD L = 0, R = 1000000;
        for (int _ = 0; _ < 100; _++) {
                DD mid = (L + R) / 2.0;
                if (check(mid)) {
                        R = mid;
                } else {
                        L = mid;
                }
        }

        cout << R << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        cout << fixed << setprecision(10);
        solution();
        return 0;
}
