/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74545290
 * Link: https://atcoder.jp/contests/abc393/tasks/abc393_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifndef ONLINE_JUDGE
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N, K; cin >> N >> K;
        int M = 0;
        vector<int> A(N);
        vector<int> cnt(1e6 + 1, 0);
        for (int i = 0; i < N; i++) {
                cin >> A[i];
                M = max(A[i], M);
                cnt[A[i]]++;
        }
        vector<lli> s(M+1, 0);
        for (int d = 2; d <= M; d++) {
                for (int n = d; n <= M; n += d) {
                        s[d] += cnt[n];
                }
        }
        vector<int> ans(M+1, 1);
        for (int d = 2; d <= M; d++) {
                if (s[d] < K) continue;
                for (int n = d; n <= M; n += d) {
                        ans[n] = max(d, ans[n]);
                }
        }
        // testv(s);
        for (const int &a : A) cout << ans[a] << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
