/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74520445
 * Link: https://atcoder.jp/contests/abc451/tasks/abc451_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <tuple>
#include <vector>
#ifndef ONLINE_JUDGE
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

constexpr int INF = 0x3f3f3f3f;

class DSU {
        public:
        int N;
        vector<int> root;
 
        DSU(int n): N(n) {
                root.resize(N);
                for (int i = 0; i < N; i++) root[i] = i;
        }
 
        bool same_component(int a, int b) {
                return find_root(a) == find_root(b);
        }
 
        int find_root(int x) {
                if (root[x] == x)
                        return x;
                root[x] = find_root(root[x]);
                return root[x];
        }
 
        void unite(int a, int b) {
                a = find_root(a);
                b = find_root(b);
                root[b] = a;
        }
};

void solution() {
        int N; cin >> N;
        vector<vector<int>> A(N, vector<int> (N));
        A[0][0] = 0;
        vector<tuple<int, int, int>> edge_list;
        for (int i = 0; i < N-1; i++) {
                for (int j = i+1; j < N; j++) {
                        cin >> A[i][j];
                        A[j][i] = A[i][j];
                        edge_list.eb(A[i][j], i, j);
                }
        }
        sort(ALL(edge_list));
        vector<vector<int>> adj(N);
        DSU dsu(N);
        for (const auto &[w, u, v] : edge_list) {
                if (dsu.same_component(u, v)) continue;
                adj[u].eb(v);
                adj[v].eb(u);
                dsu.unite(u, v);
        }
        bool yes = 1;
        for (int i = 0; i < N; i++) {
                const function<void(int, int, int)> dfs = [&](int cur, int parent, int d) -> void {
                        if (!yes) return;
                        for (const auto &nxt : adj[cur]) if (nxt != parent) {
                                if (d + A[cur][nxt] != A[i][nxt]) {
                                        yes = 0;
                                        return;
                                }
                                dfs(nxt, cur, d + A[cur][nxt]);
                        }
                };
                dfs(i, i, 0);
                if (!yes) break;
        }
        if (yes) {
                cout << "Yes\n";
        } else {
                cout << "No\n";
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
