/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74804760
 * Link: https://atcoder.jp/contests/abc438/tasks/abc438_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N, Q; cin >> N >> Q;
        vector<int> A(N+1);
        for (int i = 1; i <= N; i++) cin >> A[i];
        vector<vector<pair<int, lli>>> jmp(32, vector<pair<int, lli>>(N+1));
        for (int i = 1; i <= N; i++) jmp[0][i] = {A[i], i};
        for (int k = 1; k <= 31; k++) {
                for (int i = 1; i <= N; i++) {
                        jmp[k][i] = { jmp[k-1][jmp[k-1][i].fst].fst,
                                      jmp[k-1][jmp[k-1][i].fst].sec + jmp[k-1][i].sec };
                }
        }
        while(Q--) {
                int b, t; cin >> t >> b;
                lli ans = 0;
                for (int j = 0; j <= 31; j++) {
                        if (t & (1 << j)) {
                                ans += jmp[j][b].sec;
                                b = jmp[j][b].fst;
                        }
                }
                cout << ans << '\n';
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
