/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75102187
 * Link: https://atcoder.jp/contests/abc454/tasks/abc454_f
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int N, M; cin >> N >> M;
        vector<lli> A(N);
        for (auto &x : A) cin >> x;
        vector<lli> B(N/2);
        for (int i = 0; i < N/2; i++) {
                B[i] = (A[N-i-1] - A[i] + M) % M;
        }
        B.eb(0);
        vector<lli> diff_array(N/2);
        for (int i = 0; i < N/2; i++) diff_array[i] = (B[i+1] - B[i] + M) % M;
        sort(ALL(diff_array));
        lli pre = 0, suf = 0;
        for (int i = 0; i < N/2; i++) suf += M - diff_array[i];
        lli ans = max(pre, suf);
        for (int i = 0; i < N/2; i++) {
                pre += diff_array[i];
                suf -= M - diff_array[i];
                ans = min(max(pre, suf), ans);
        }
        cout << ans << '\n';
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        int T; cin >> T;
        while (T--)
                solution();
        return 0;
}
