/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73925890
 * Link: https://atcoder.jp/contests/abc448/tasks/abc448_d
 */

#include <iostream>
#include <functional>
#include <set>
#include <map>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<int> as(N);
        for (auto &a : as) cin >> a;
        vector adj(N, vector<int>());
        for (int i = 0; i < N-1; i++) {
                int u, v; cin >> u >> v;
                --u; --v;
                adj[u].eb(v);
                adj[v].eb(u);
        }
        map<int, int> freq;
        vector<int> ans(N);
        function<void(int, int, bool)>
        dfs = [&](int cur, int parent, bool yes)->void {
                if (freq[as[cur]] != 0) {
                        yes = 1;
                }
                ++freq[as[cur]];
                ans[cur] = yes;
                for (const auto &nxt : adj[cur]) if (nxt != parent) {
                        dfs(nxt, cur, yes);
                }
                --freq[as[cur]];
        };
        dfs(0, 0, 0);
        for (int i = 0; i < N; ++i) {
                if (ans[i]) cout << "Yes\n";
                else cout << "No\n";
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
