/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75880743
 * Link: https://atcoder.jp/contests/abc458/tasks/abc458_d
 */

#include <iostream>
#include <set>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        int X;
        cin >> X;
        int Q;
        cin >> Q;
        multiset<int> s, t;
        t.insert(X);
        const auto f = [&](int k) {
                if (k < X) s.insert(k);
                else t.insert(k);
        };
        for (int i = 1; i <= Q; i++) {
                int A, B;
                cin >> A >> B;
                f(A);
                f(B);
                while (SZ(s) >= SZ(t)) {
                        int k = *s.rbegin();
                        t.insert(k);
                        s.erase(--s.end());
                }
                while (SZ(t) > SZ(s) + 1) {
                        int k = *t.begin();
                        s.insert(k);
                        t.erase(t.begin());
                }
                X = *t.begin();
                cout << X << '\n';
        }
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
