/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74877507
 * Link: https://atcoder.jp/contests/abc453/tasks/abc453_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <queue>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

constexpr int dx[] = {0, 0, -1, 1};
constexpr int dy[] = {-1, 1, 0, 0};

void solution() {
        int H, W; cin >> H >> W;
        vector<string> grid(H);
        int sx, sy, gx, gy;
        for (int i = 0; i < H; i++) {
                cin >> grid[i];
                for (int j = 0; j < W; j++) {
                        if (grid[i][j] == 'S') {
                                sx = j;
                                sy = i;
                        }
                        if (grid[i][j] == 'G') {
                                gx = j;
                                gy = i;
                        }
                }
        }
        queue<tuple<int, int, int>> qu;
        qu.emplace(sx, sy, 0);
        vector visited(4, vector<vector<int>> (H, vector<int> (W, 0)));
        vector f(4, vector<vector<int>> (H, vector<int> (W, 0)));
        const auto out_of_bound = [&](int x, int y) -> bool {
                return x < 0 or x >= W or y < 0 or y >= H;
        };
        const auto go = [&](int x, int y, int k, int d) -> void {
                int nx = x + dx[k], ny = y + dy[k];
                if (not out_of_bound(nx, ny) and not visited[k][ny][nx]) {
                        qu.emplace(nx, ny, k);
                        f[k][ny][nx] = d;
                        visited[k][ny][nx] = 1;
                }
        };
        while (not qu.empty()) {
                auto [x, y, d] = qu.front(); qu.pop();
                // test(x, y);
                if (x == gx and y == gy) {
                        cout << "Yes\n";
                        string route = "";
                        int nx = x, ny = y, nd = f[d][y][x];
                        while (nx != sx or ny != sy) {
                                route += "UDLR"[d];
                                ny -= dy[d];
                                nx -= dx[d];
                                test(nx, ny, d);
                                d = nd;
                                nd = f[nd][ny][nx];
                        }
                        test(nx, ny, d);
                        reverse(ALL(route));
                        cout << route << '\n';
                        return;
                } else if (grid[y][x] == '#') {
                        continue;
                } else if (grid[y][x] == 'o') {
                        go(x, y, d, d);
                } else if (grid[y][x] == 'x') {
                        for (int k = 0; k < 4; k++) if (k != d) go(x, y, k, d);
                } else {
                        for (int k = 0; k < 4; k++) go(x, y, k, d);
                }
        }
        cout << "No\n";
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
