/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74906249
 * Link: https://atcoder.jp/contests/abc453/tasks/abc453_e
 */

#include <algorithm>
#include <atcoder/modint>
#include <array>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;
using mint = atcoder::modint998244353;

mint frac[400005];
void precalc_frac() {
        frac[0] = 1;
        for (int i = 1; i <= 4e5; i++) {
                frac[i] = frac[i-1] * i;
        }
}

mint nCr(int n, int r) {
        if (n < 0) return 0;
        if (r < 0) return 0;
        if (r > n) return 0;
        return frac[n] / (frac[r] * frac[n-r]);
}

void solution() {
        int N; cin >> N;
        vector<int> L(N), R(N);
        vector<vector<int>> proc(N+1);
        for (int i = 0; i < N; i++) {
                cin >> L[i] >> R[i];
                proc[L[i]].eb(i);
                proc[R[i]+1].eb(i);
                proc[N-R[i]].eb(i);
                proc[N-L[i]+1].eb(i);
        }

        // case 1: L <= i <= R and L <= (N-i) <= R (Team A or B)
        // case 2: L <= i <= R                     (Team A)
        // case 3: L <= (N-i) <= R                 (Team B)
        // case 4: None
        int match[2][2] = {};
        match[0][0] = N;
        vector<int> aok(N+1, 0), bok(N+1, 0);
        mint ans = 0;
        for (int i = 1; i <= N-1; i++) { // i people in team A
                for (const int &z : proc[i]) {
                        match[aok[z]][bok[z]]--;
                        if (L[z] <= i and i <= R[z]) aok[z] = 1;
                        else                         aok[z] = 0;
                        if (L[z] <= N-i and N-i <= R[z]) bok[z] = 1;
                        else                             bok[z] = 0;
                        match[aok[z]][bok[z]]++;
                }
                if (match[0][0] == 0 and match[1][0] <= i and match[0][1] <= N-i) {
                        ans += nCr(match[1][1], i-match[1][0]);
                }
        }
        cout << ans.val() << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        precalc_frac();
        solution();
        return 0;
}
