/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 72997900
 * Link: https://atcoder.jp/contests/abc436/tasks/abc436_c
 */

#include <iostream>
#include <set>
#include <utility>

using namespace std;
const int dx[4] = {0, 1, 0, 1};
const int dy[4] = {0, 0, 1, 1};

int main() {
        cin.tie(0)->sync_with_stdio(0);
        int N, M;
        cin >> N >> M;
        set<pair<int, int>> st;
        int ans = 0;
        for (int i = 0; i < M; i++) {
                int Ri, Ci;
                cin >> Ri >> Ci;
                bool flag = 1;
                for (int k = 0; k < 4; k++) {
                        if (st.find({Ri+dx[k], Ci+dy[k]}) != st.end()) {
                                flag = 0;
                                break;
                        }
                }
                if (flag) {
                        for (int k = 0; k < 4; k++) {
                                st.insert({Ri+dx[k], Ci+dy[k]});
                        }
                        ans += 1;
                }
        }
        cout << ans << '\n';
        return 0;
}
