/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73716735
 * Link: https://atcoder.jp/contests/abc447/tasks/abc447_c
 */

#include <functional>
#include <iostream>
#include <string>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        string S, T;
        cin >> S >> T;
        int a = 0, b = 0;
        int ans = 0;
        while (a < SZ(S) or b < SZ(T)) {
                if (S[a] == T[b]) {
                        if (a < SZ(S) and b < SZ(T)) {
                                ++a; ++b;
                        } else {
                                cout << "-1";
                                return;
                        }
                } else if (S[a] == 'A' and T[b] != 'A') {
                        if (a < SZ(S)) {
                                ++a;
                                ++ans;
                        } else {
                                cout << "-1";
                                return;
                        }
                } else if (S[a] != 'A' and T[b] == 'A') {
                        if (b < SZ(T)) {
                                ++b;
                                ++ans;
                        } else {
                                cout << "-1";
                                return;
                        }
                } else {
                        cout << "-1";
                        return;
                }
        }
        cout << ans;
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
