/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74725046
 * Link: https://atcoder.jp/contests/abc452/tasks/abc452_f
 */

#include <algorithm>
#include <atcoder/fenwicktree>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; lli K; cin >> N >> K;
        vector<int> P(N);
        for (int &p : P) cin >> p;
        const auto f = [&](lli K) -> lli {
                atcoder::fenwick_tree<int> fw(N+1);
                lli ans = 0;
                lli inv_cnt = 0;
                for (int l = 0, r = 0; l < N; l++) { // [l, r)
                        for (r = max(l, r); r < N and inv_cnt + fw.sum(P[r], N+1) <= K; r++) {
                                inv_cnt += fw.sum(P[r], N+1);
                                fw.add(P[r], +1);
                        }
                        ans += r - l;
                        inv_cnt -= fw.sum(0, P[l]);
                        fw.add(P[l], -1);
                }
                return ans;
        };
        cout << f(K) - (K == 0 ? 0 : f(K-1)) << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
