/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73721108
 * Link: https://atcoder.jp/contests/abc447/tasks/abc447_b
 */

#include <algorithm>
#include <iostream>
#include <map>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        map<char, int> freq;
        int maxFreq = 0;
        string S;
        cin >> S;
        for (char c : S) {
                ++freq[c];
                maxFreq = max(freq[c], maxFreq);
        }
        map<char, bool> isMax;
        for (char c = 'a'; c <= 'z'; ++c) {
                if (freq[c] == maxFreq)
                        isMax[c] = 1;
                else
                        isMax[c] = 0;
        }
        string res;
        for (char &c : S) {
                if (!isMax[c])
                        res += c;
        }
        cout << res << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
