/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73978279
 * Link: https://atcoder.jp/contests/abc448/tasks/abc448_e
 */

#include <functional>
#include <iostream>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int K, M; cin >> K >> M;
        const lli MOD = M * 10007;
        const function<lli(lli a, lli p)> fpow = [&](lli a, lli p)->lli {
                lli res = 1;
                while (p) {
                        if (p & 1LL) res = (res * a) % MOD;
                        a = (a * a) % MOD;
                        p >>= 1;
                }
                return res;
        };
        vector<int> c(K), l(K);
        for (int i = 0; i < K; i++) cin >> c[i] >> l[i];
        #define R_POW_2_LIMIT 31
        // R_k = 1...[k]...1
        vector<lli> R_pow_of_2(R_POW_2_LIMIT+1);
        R_pow_of_2[0] = 1;
        for (int i = 1; i <= R_POW_2_LIMIT; i++)
                R_pow_of_2[i] = (R_pow_of_2[i-1] * fpow(10, 1 << (i-1)) + R_pow_of_2[i-1]) % MOD; // R_(2^i)
        const function<lli(int)> get_R = [&](int l)->lli {
                lli R = 0;
                for (int j = R_POW_2_LIMIT; j >= 0; j--) if (l & (1 << j))
                        R = (R * fpow(10, (1 << j)) + R_pow_of_2[j]) % MOD;
                return R;
        };
        lli res = 0, tz = 0;
        for (int i = K-1; i >= 0; i--) {
                lli c_w_tz = (c[i] * fpow(10, tz)) % MOD;
                res += c_w_tz * get_R(l[i]);
                if (res >= MOD) res %= MOD;
                tz += l[i];
        }
        cout << res / M << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
