/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 69854604
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_c
 */

#include <iostream>
#include <set>
#include <utility>
#define fastio cin.tie(0)->sync_with_stdio(false)
#define eb emplace_back
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x) { \
    for (auto i : x) cout << i << ' '; \
    cout << endl; \
}
#define pii pair<int, int>
#define pll pair<lli, lli>
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()
#define MP(x, y) make_pair((x), (y))
#define SQ(x) ((x)*(x))
#define SZ(x) ((int) x.size())

using namespace std;
typedef long long int lli;

template <typename A, typename B>
ostream& operator << (ostream& o, pair<A, B> a) {
    return o << a.first << ' ' << a.second;
}
template <typename A, typename B>
istream& operator >> (istream& o, pair<A, B> &a) {
    return o >> a.first >> a.second;
}

constexpr int INF = 1e9 + 7;

void solve() {
    int N, Q;
    cin >> N >> Q;
    set<pair<int, int>> st;
    for (int i = 1; i <= N; i++) {
        st.emplace(i, 1);
    }
    for (int i = 0; i < Q; i++) {
        // for (auto x : st) {
        //     cerr << x << ' ';
        // } cerr << endl;
        int x, y; cin >> x >> y;
        auto lb = st.upper_bound(MP(x, INF));
        auto it = lb;
        int cnt = 0;
        while (it != st.begin()) {
            --it;
            cnt += it->second;
        }
        st.erase(st.begin(), lb);
        cout << cnt << '\n';

        auto p = st.lower_bound(MP(y, 0));
        if (p->first == y) {
            cnt += p->second;
            st.erase(p);
        }
        st.emplace(y, cnt);
    }
}

int main() {
    fastio;
    solve();
    return 0;
}