/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75436779
 * Link: https://atcoder.jp/contests/abc456/tasks/abc456_b
 */

#include <functional>
#include <iostream>
#include <iomanip>
#include <set>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) std::cout << i << ' '; std::cout << std::endl; }
#define printlnv(x) { for (auto i : (x)) std::cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) std::begin(x), std::end(x)
#define rALL(x) std::rbegin(x), std::rend(x)
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        vector<int> A(6), B(6), C(6);
        for (auto &x : A) cin >> x;
        for (auto &x : B) cin >> x;
        for (auto &x : C) cin >> x;
        double cnt = 0;
        for (int i = 0; i < 6; i++) {
                for (int j = 0; j < 6; j++) {
                        for (int k = 0; k < 6; k++) {
                                set<int> st;
                                st.insert(A[i]);
                                st.insert(B[j]);
                                st.insert(C[k]);
                                if (st == set<int>{4, 5, 6}) cnt += 1;
                        }
                }
        }
        cout << cnt / 216.0 << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        cout << fixed << setprecision(10);
        solution();
        return 0;
}

