/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75241630
 * Link: https://atcoder.jp/contests/abc455/tasks/abc455_c
 */

#include <functional>
#include <iostream>
#include <map>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int N, K;
        cin >> N >> K;
        map<lli, int> freq;
        lli sum = 0;
        for (int _ = 0; _ < N; _++) {
                int A;
                cin >> A;
                freq[A]++;
                sum += A;
        }
        vector<lli> v;
        for (const auto &[key, val] : freq) {
                v.eb(key * val);
        }
        sort(rALL(v));
        for (int i = 0; i < K; i++) {
                if (i >= v.size())
                        break;
                sum -= v[i];
        }
        cout << sum << '\n';
}

int main() {
        ios_base::sync_with_stdio(false);
        cin.tie(nullptr);
        solution();
        return 0;
}
