/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 71703319
 * Link: https://atcoder.jp/contests/abc436/tasks/abc436_d
 */

#include <cctype>
#include <iostream>
#include <queue>
#include <utility>
#include <tuple>
#include <vector>

#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())

using namespace std;
using lli = long long int;

const int dj[] = {0, 0, -1, 1};
const int di[] = {1, -1, 0, 0};

void solution() {
        int H, W;
        cin >> H >> W;
        vector<vector<char>> g(H+2, vector<char> (W+2));
        vector<vector<bool>> v(H+2, vector<bool> (W+2, 1));
        vector<vector<pair<int, int>>> jmp(1024);
        for (int i = 1; i <= H; i++) {
                for (int j = 1; j <= W; j++) {
                        cin >> g[i][j];
                        if (isalpha(g[i][j])) {
                                v[i][j] = 0;
                                jmp[g[i][j]].push_back({i, j});
                        }
                        if (g[i][j] == '.') v[i][j] = 0;
                }
        }
        queue<tuple<int, int, int>> qu;
        qu.push({1, 1, 0});

        while (!qu.empty()) {
                const auto &[i, j, d] = qu.front();
                qu.pop();
                // test(i);
                // test(j);
                if (i == H and j == W) {
                        cout << d << '\n';
                        return;
                }
                if (i <= 0 or j <= 0 or i > H or j > W) continue;
                if (v[i][j]) continue;
                v[i][j] = 1;
                for (int k = 0; k < 4; k++) {
                        int ni = i + di[k], nj = j + dj[k];
                        if (ni <= 0 or nj <= 0 or ni > H or nj > W) continue;
                        if (!v[ni][nj]) {
                                qu.push({ni, nj, d+1});
                        }
                }
                if (isalpha(g[i][j])) {
                        for (const auto &[ni, nj] : jmp[g[i][j]]) {
                                if (ni <= 0 or nj <= 0 or ni > H or nj > W) continue;
                                if (!v[ni][nj]) {
                                        qu.push({ni, nj, d+1});
                                        jmp[g[i][j]] = {};
                                }
                        }
                }
        }
        cout << -1 << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
