/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74131424
 * Link: https://atcoder.jp/contests/abc449/tasks/abc449_d
 */

#include <algorithm>
#include <cmath>
#include <iostream>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int L, R, D, U; cin >> L >> R >> D >> U;
        lli ans = 0;
        // |x| > |y| and x % 2 == 0
        for (int x = L; x <= R; x++) if (x % 2 == 0) {
                int ub = min(U,  abs(x)-1);
                int lb = max(D, -abs(x)+1);
                ans += max(ub-lb+1, 0);
        }
        // |y| >= |x| and y % 2 == 0
        for (int y = D; y <= U; y++) if (y % 2 == 0) {
                int ub = min(R,  abs(y));
                int lb = max(L, -abs(y));
                ans += max(ub-lb+1, 0);
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
