/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74706830
 * Link: https://atcoder.jp/contests/abc452/tasks/abc452_e
 */

#include <algorithm>
#include <atcoder/modint>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;
using mint = atcoder::modint998244353;

void solution() {
        int N, M; cin >> N >> M;
        vector<lli> A(N+1, 0), B(M+1, 0);
        for (int i = 1; i <= N; i++) cin >> A[i];
        for (int i = 1; i <= M; i++) cin >> B[i];
        // A_i * B_j * (i mod j) = B_j * (A_i * i - A_i * jk)
        // sum1 = A_i * i
        // sum2 = A_i
        vector<mint> sum1(N+1, 0), sum2(N+1, 0);
        for (int i = 1; i <= N; i++) sum1[i] = sum1[i-1] + A[i] * i;
        for (int i = 1; i <= N; i++) sum2[i] = sum2[i-1] + A[i];
        mint ans = 0;
        for (int j = 1; j <= M; j++) {
                mint s = 0;
                for (int k = 0; k * j <= N; k++) {
                        int l = k * j;
                        int r = min( (k+1)*j-1 , N);
                        if (l == 0) {
                                s += sum1[r];
                                s -= (sum2[r]) * (k * j);
                        } else {
                                s += sum1[r] - sum1[l-1];
                                s -= (sum2[r] - sum2[l-1]) * (k * j);
                        }
                }
                ans += s * B[j];
        }
        cout << ans.val() << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
