/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73732644
 * Link: https://atcoder.jp/contests/abc447/tasks/abc447_e
 */

#include <iostream>
#include <utility>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

class DSU {
        public:
        int N;
        vector<int> root;
 
        DSU(int n): N(n) {
                root.resize(N+1);
                for (int i = 1; i <= N; i++) {
                        root[i] = i;
                }
        }
 
        bool same_component(int a, int b) {
                return find_root(a) == find_root(b);
        }
 
        int find_root(int x) {
                if (root[x] == x)
                        return x;
                root[x] = find_root(root[x]);
                return root[x];
        }
 
        void unite(int a, int b) {
                a = find_root(a);
                b = find_root(b);
                root[b] = a;
        }
};

constexpr int MOD = 998244353;

int fpow(unsigned long long a, int b, int p) {
        unsigned long long res = 1;
        while (b) {
                if (b & 1) res = (res * a) % p;
                b >>= 1;
                a = a * a % p;
        }
        return res;
}

void solution() {
        int N, M;
        cin >> N >> M;
        vector<pair<int, int>> edges(M);
        for (auto &[u, v] : edges) cin >> u >> v;
        DSU dsu(N);
        lli ans = 0;
        int components = N;
        for (int i = M-1; i >= 0; i--) {
                auto &[u, v] = edges[i];
                if (dsu.same_component(u, v)) continue;
                if (components > 2) {
                        dsu.unite(u, v);
                        --components;
                } else {
                        ans += fpow(2, i+1, MOD);
                        if (ans >= MOD) ans %= MOD;
                }
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
