/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75460916
 * Link: https://atcoder.jp/contests/abc456/tasks/abc456_e
 */

#include <functional>
#include <iostream>
#include <vector>
#include <queue>
#include <utility>
#include <tuple>
#include <string>
#include <map>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) std::cout << i << ' '; std::cout << std::endl; }
#define printlnv(x) { for (auto i : (x)) std::cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) std::begin(x), std::end(x)
#define rALL(x) std::rbegin(x), std::rend(x)
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        int N, M;
        cin >> N >> M;
        vector<vector<int>> al(N+1);
        for (int i = 1; i <= N; i++) al[i].eb(i);
        for (int _ = 0; _ < M; _++) {
                int u, v;
                cin >> u >> v;
                al[u].eb(v);
                al[v].eb(u);
        }
        int W;
        cin >> W;
        vector<string> S(N+1);
        for (int i = 1; i <= N; i++) {
                cin >> S[i];
        }
        bool ok = 0;
        map<pair<int, int>, int> state;
        const auto dfs = [&](this auto&& self, int cur, int d) -> void {
                if (ok) return;
                if (state[{cur, d%W}] == 2) return;
                if (state[{cur, d%W}] == 1) {
                        cout << "Yes\n";
                        ok = 1;
                        return;
                }
                state[{cur, d%W}] = 1;
                for (const auto &nxt : al[cur]) if (S[nxt][(d+1)%W] == 'o' and !ok) {
                        self(nxt, d+1);
                }
                state[{cur, d%W}] = 2;
        };
        for (int i = 1; i <= N; i++) if (!ok) {
                if (S[i][0] == 'o' and state[{i, 0}] == 0) dfs(i, 0);
        }
        if (!ok) cout << "No\n";
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        int T; cin >> T;
        while (T--)
                solution();
        return 0;
}
