/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74301898
 * Link: https://atcoder.jp/contests/abc450/tasks/abc450_c
 */

#include <iostream>
#include <functional>
#include <string>
#include <vector>
#include <utility>
#include <queue>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

constexpr int di[] = {0, 0, -1, 1};
constexpr int dj[] = {-1, 1, 0, 0};

void solution() {
        int H, W; cin >> H >> W;
        vector<string> grid(H);
        for (string &s : grid) cin >> s;
        vector<vector<bool>> available(H, vector<bool> (W, 0));
        for (int i = 0; i < H; i++) for (int j = 0; j < W; j++) if (grid[i][j]=='.') available[i][j] = 1;
        vector<vector<int>> component_id(H, vector<int> (W));
        vector<int> is_surrounded(H*W, 1);
        const function is_boundary = [&](int i, int j)->bool{
                return (i == 0) or (i == H-1) or (j == 0) or (j == W-1);
        };
        const function bfs = [&](int i, int j)->void{
                int cid = component_id[i][j];
                queue<pair<int, int>> qu;
                qu.push({i, j});
                available[i][j] = 0;
                while (not qu.empty()) {
                        auto [ci, cj] = qu.front();
                        if (is_boundary(ci, cj)) is_surrounded[cid] = 0;
                        qu.pop();
                        for (int k = 0; k < 4; k++) {
                                int ni = ci + di[k], nj = cj + dj[k];
                                if (ni < 0 or ni >= H or nj < 0 or nj >= W) continue;
                                if (available[ni][nj]) {
                                        available[ni][nj] = 0;
                                        component_id[ni][nj] = cid;
                                        qu.push({ni, nj});
                                }
                        }
                }
        };
        int components = 0;
        for (int i = 1; i < H-1; i++) {
                for (int j = 1; j < W-1; j++) {
                        if (available[i][j]) {
                                component_id[i][j] = components++;
                                bfs(i, j);
                        }
                }
        }
        int ans = 0;
        for (int i = 0; i < components; i++) if (is_surrounded[i]) ans++;
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
