/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75896199
 * Link: https://atcoder.jp/contests/abc458/tasks/abc458_e
 */

#include <atcoder/modint>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

using mint = atcoder::modint998244353;

constexpr int maxN = 3e6;
mint frac[maxN+1];

void precompute_frac() {
        frac[0] = 1;
        for (int i = 1; i <= maxN; i++) {
                frac[i] = frac[i-1] * i;
        }
}

mint bionom(int n, int m) {
        if (n < m or m < 0) return 0;
        return frac[n] / (frac[m] * frac[n-m]);
}

// https://atcoder.jp/contests/abc458/editorial/20467

void solution() {
        int X1, X2, X3;
        cin >> X1 >> X2 >> X3;
        mint ans = 0;
        for (int k = 1; k <= X2; k++) {
                mint tmp = 1;
                tmp *= bionom(X2+1, k);
                tmp *= bionom(X1-1, k-1);
                tmp *= bionom(X3+X2-k, X2-k);
                ans += tmp;
        }
        cout << ans.val() << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        precompute_frac();
        solution();
        return 0;
}
