/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75002905
 * Link: https://atcoder.jp/contests/abc438/tasks/abc438_f
 */

#include <algorithm>
#include <atcoder/fenwicktree>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<vector<int>> adj(N+1);
        for (int i = 0; i < N-1; i++) {
                int u, v; cin >> u >> v;
                adj[u].eb(v);
                adj[v].eb(u);
        }

        vector<vector<int>> jump(32, vector<int>(N+1, 0));
        vector<int> tin(N+1), tout(N+1);
        vector<int> depth(N+1);
        depth[0] = 1;
        int timer = 0;
        const function<void(int, int)> dfs_find_order = [&](int cur, int parent) -> void {
                depth[cur] = depth[parent] + 1;
                tin[cur] = timer++;
                
                for (const int &nxt : adj[cur]) {
                        if (nxt == parent) {
                                jump[0][cur] = parent;
                        } else  {
                                dfs_find_order(nxt, cur);
                        }
                }
                
                tout[cur] = timer++;
        };
        dfs_find_order(0, 0);
        jump[0][0] = 0;
        for (int k = 1; k <= 31; k++) {
                for (int i = 1; i <= N; i++) {
                        jump[k][i] = jump[k - 1][ jump[k - 1][i] ];
                }
        }

        const auto a_is_anc_of_b = [&](int a, int b) -> bool {
                return tin[a] <= tin[b] and tout[a] >= tout[b];
        };

        const auto lca = [&](int a, int b) -> int {
                if (a_is_anc_of_b(a, b)) return a;
                if (a_is_anc_of_b(b, a)) return b;
 
                for (int j = 31; j >= 0; j--) {
                        if (!a_is_anc_of_b(jump[j][a], b)) {
                                a = jump[j][a];
                        }
                }

                return jump[0][a];
        };

        const auto distance = [&](int a, int b) -> int {
                return depth[a] + depth[b] - 2*depth[lca(a, b)];
        };

        vector<int> sz(N);
        const function<void(int, int)> dfs_sz = [&](int cur, int parent) -> void {
                sz[cur] = 1;
                for (const auto &nxt : adj[cur]) {
                        if (nxt != parent) {
                                dfs_sz(nxt, cur);
                                sz[cur] += sz[nxt];
                        }
                }
        };
        dfs_sz(0, 0);

        lli ans = (lli) N * (N+1) / 2;
        for (const auto &v : adj[0]) ans -= (lli) sz[v] * (sz[v] + 1) / 2;

        const auto get_child = [&](int anc, int child) -> int {
                for (int j = 31; j >= 0; j--) {
                        if (depth[child] - (1 << j) > depth[anc]) child = jump[j][child];
                }
                return child;
        };

        int x = 0, y = 0;
        for (int k = 1; k < N; k++) { 
                if (distance(x, y) == distance(x, k) + distance(k, y)) {
                } else if (distance(x, k) == distance(x, y) + distance(y, k)) {
                        y = k;
                } else if (distance(y, k) == distance(x, y) + distance(x, k)) {
                        x = k;
                } else {
                        break;
                }
                lli sx = 0, sy = 0;
                if (a_is_anc_of_b(x, y)) {
                        sy = sz[y];
                        sx = N - sz[get_child(x, y)];
                } else if (a_is_anc_of_b(y, x)) {
                        sx = sz[x];
                        sy = N - sz[get_child(y, x)];
                } else {
                        sx = sz[x];
                        sy = sz[y];
                }
                ans += sx * sy; 
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
