/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74805283
 * Link: https://atcoder.jp/contests/abc438/tasks/abc438_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<lli> A(N+1, 0), B(N+1, 0), C(N+1, 0);
        for (int i = 1; i <= N; i++) cin >> A[i];
        for (int i = 1; i <= N; i++) cin >> B[i];
        for (int i = 1; i <= N; i++) cin >> C[i];
        vector<lli> dpA(N+1, 0), dpB(N+1, 0), dpC(N+1, 0);
        for (int i = 1; i <= N; i++) dpA[i] = dpA[i-1] + A[i];
        for (int i = 2; i <= N; i++) dpB[i] = max(dpA[i-1], dpB[i-1]) + B[i];
        for (int i = 3; i <= N; i++) dpC[i] = max(dpB[i-1], dpC[i-1]) + C[i];
        cout << dpC[N] << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
