/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 69832823
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_a
 */

#include <iostream>
#include <string>
#define fastio cin.tie(0)->sync_with_stdio(false)
#define eb emplace_back
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x) { \
    for (auto i : x) cout << i << ' '; \
    cout << endl; \
}
#define pii pair<int, int>
#define pll pair<lli, lli>
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()
#define MP(x, y) make_pair((x), (y))
#define SQ(x) ((x)*(x))
#define SZ(x) ((int) x.size())

using namespace std;
typedef long long int lli;

template <typename A, typename B>
ostream& operator << (ostream& o, pair<A, B> a) {
    return o << a.first << ' ' << a.second;
}
template <typename A, typename B>
istream& operator >> (istream& o, pair<A, B> &a) {
    return o >> a.first >> a.second;
}

int p(string s) {
    if (s == "Ocelot") return 1;
    if (s == "Serval") return 2;
    if (s == "Lynx") return 3;
}

void solve() {
    string x, y;
    cin >> x >> y;
    cout << ((p(x) < p(y)) ? "No" : "Yes");
}

int main() {
    fastio;
    solve();
    return 0;
}