/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 76008601
 * Link: https://atcoder.jp/contests/abc436/tasks/abc436_f
 */

#include <atcoder/fenwicktree>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        int N;
        cin >> N;
        vector<int> B(N);
        for (auto &b : B) cin >> b;
        atcoder::fenwick_tree<int> fwt(N);
        lli ans = 0;
        for (int i = 0; i < N; i++) {
                lli left = fwt.sum(0, B[i]), right = (B[i] - 1 - left);
                ans += (left + 1) * (right + 1);
                fwt.add(B[i]-1, 1);
        }
        cout << ans << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}