/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 76066517
 * Link: https://atcoder.jp/contests/abc459/tasks/abc459_d
 */

#include <iostream>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        string S;
        cin >> S;
        int N = SZ(S);
        vector<int> freq(26, 0);
        for (char c: S) freq[c-'a']++;
        for (int i = 0; i < 26; i++) {
                if (freq[i] > (N + 1) / 2) {
                        cout << "No\n";
                        return;
                }
        }
        cout << "Yes\n";
        int last = 67;
        for (int i = 0; i < N; i++) {
                int max_cnt = 0;
                int cur;
                for (int j = 0; j < 26; j++) if (j != last) {
                        if (freq[j] > max_cnt) {
                                cur = j;
                                max_cnt = freq[j];
                        }
                }
                freq[cur]--;
                cout << (char) (cur + 'a');
                last = cur;
        }
        cout << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        int T;
        cin >> T;
        while (T--)
                solution();
        return 0;
}
