/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75200710
 * Link: https://atcoder.jp/contests/abc450/tasks/abc450_e
 */

#include <array>
#include <cassert>
#include <functional>
#include <iostream>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

const lli INF = 1E18;

void solution() {
        string X, Y;
        cin >> X >> Y;

        const int N = X.size(), M = Y.size();

        vector<array<lli, 27>> prex(N+1), prey(M+1);
        prex[0] = {0}, prey[0] = {0};
        for (int i = 0; i < N; i++) {
                prex[i+1] = prex[i];
                prex[i+1][X[i]-'a']++;
                prex[i+1][26]++;
        }
        for (int i = 0; i < M; i++) {
                prey[i+1] = prey[i];
                prey[i+1][Y[i]-'a']++;
                prey[i+1][26]++;
        }

        vector<array<lli, 27>> f;
        f.emplace_back(prex[N]);
        f.emplace_back(prey[M]);

        while (f.back()[26] < INF) {
                auto res = f.back();
                for (int i = 0; i < 27; i++) {
                        res[i] += f.end()[-2][i];
                }
                f.emplace_back(res);
        }

        const function<lli(int, lli, int)> qry = [&](int k, lli idx, int c) -> lli {
                if (k == 0) {
                        assert(idx <= N);
                        return prex[idx][c];
                }
                if (k == 1) {
                        assert(idx <= M);
                        return prey[idx][c];
                }
                if (idx < f[k-1][26]) {
                        return qry(k-1, idx, c);
                }
                return f[k-1][c] + qry(k-2, idx-f[k-1][26], c);
        };

        const int K = f.size() - 1;

        int Q;
        cin >> Q;
        for (int _ = 0; _ < Q; _++) {
                lli L, R;
                char c;
                cin >> L >> R >> c;
                cout << qry(K, R, c-'a') - qry(K, L-1, c-'a') << '\n';
        }
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}