/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73709114
 * Link: https://atcoder.jp/contests/abc447/tasks/abc447_d
 */

#include <algorithm>
#include <iostream>
#include <ranges>
#include <string>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        string S; cin >> S;
        vector<int> is, js, ks;
        for (int i = 0; i < SZ(S); i++) {
                if (S[i] == 'A')
                        is.eb(i);
                if (S[i] == 'B')
                        js.eb(i);
                if (S[i] == 'C')
                        ks.eb(i);
        }
        auto ie = is.end(), je = js.end();
        reverse(ALL(ks));
        int ans = 0;
        for (const int &k : ks) {
                auto jj = upper_bound(js.begin(), je, k);
                if (jj == js.begin()) {
                        cout << ans << '\n';
                        return;
                }
                --jj;
                je = jj;
                auto ii = upper_bound(is.begin(), ie, *jj);
                if (ii == is.begin()) {
                        cout << ans << '\n';
                        return;
                }
                --ii;
                ie = ii;
                ans++;
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
