/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74882816
 * Link: https://atcoder.jp/contests/abc453/tasks/abc453_c
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <queue>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        queue<pair<lli, int>> qu;
        int ans = 0;
        const auto go = [&](lli x, lli L, int c) {
                if ((x > 0 and x + L < 0) or (x < 0 and x + L > 0)) {
                        qu.emplace(x+L, c+1);
                        ans = max(ans, c+1);
                } else {
                        qu.emplace(x+L, c);
                }
        };
        qu.emplace(1LL, 0);
        for (int i = 0; i < N; i++) {
                lli L; cin >> L;
                for (int j = 0; j < (1 << i); j++) {
                        auto [x, c] = qu.front(); qu.pop();
                        go(x, L*2, c);
                        go(x, -2*L, c);
                }
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
