/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73901437
 * Link: https://atcoder.jp/contests/abc448/tasks/abc448_b
 */

#include <algorithm>
#include <iostream>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N, M;
        cin >> N >> M;
        vector<int> cs(M+1);
        for (int i = 1; i <= M; i++) cin >> cs[i];
        int ans = 0;
        while (N--) {
                int a, b; cin >> a >> b;
                ans += min(b, cs[a]);
                cs[a] -= min(b, cs[a]);
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
