/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73741479
 * Link: https://atcoder.jp/contests/abc447/tasks/abc447_f
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<vector<int>> adj(N);
        for (int i = 0; i < N-1; i++) {
                int u, v;
                cin >> u >> v;
                --u; --v;
                adj[u].emplace_back(v);
                adj[v].emplace_back(u);
        }
        int ans = 1;
        // dp[v] : (centipede subtree ends with v) + (1 edge connected to parent)
        function<int(int, int)>
        dfs_dp_up = [&](int cur, int parent)->int {
                vector<int> dp;
                for (const int &child : adj[cur]) if (child != parent){
                        dp.emplace_back(dfs_dp_up(child, cur));
                }
                sort(rALL(dp));
                int dp_up = 0;
                if (SZ(adj[cur]) >= 4) {
                        dp_up = dp[0] + 1;
                        ans = max(dp[0] + dp[1] + 1, ans); // cur as midpoint
                }
                if (SZ(adj[cur]) == 3) {
                        dp_up = 1; // 2 vertices connected + 1 edge to parent
                        ans = max(dp[0] + 1, ans);
                }
                return dp_up;
        };
        dfs_dp_up(0, -1);
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        int T; cin >> T;
        while (T-->0)
                solution();
        return 0;
}
