/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74335935
 * Link: https://atcoder.jp/contests/abc449/tasks/abc449_f
 */

#include <algorithm>
#include <array>
#include <functional>
#include <iostream>
#include <set>
#include <tuple>
#include <utility>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int H, W, h, w, N; cin >> H >> W >> h >> w >> N;
        vector<array<lli, 3>> events; // (r, c, in_out)
        events.reserve(2*N);
        // sweep on R axis
        for (int i = 0; i < N; i++) {
                int R, C; cin >> R >> C;
                R--; C--;
                events.push_back({R-h+1, C-w+1, +1});
                events.push_back({R+1  , C-w+1, -1});
        }
        sort(events.begin(), events.end(), [](const auto& a, const auto& b) {
                if (a[0] != b[0]) return a[0] < b[0];
                if (a[2] != b[2]) return a[2] < b[2];
                return a[1] < b[1];
        });
        multiset<lli> st; // C axis
        st.insert(-w);
        st.insert(W-w+1);
        const function gap = [&](lli l, lli r)->lli{
                // [l, r)
                return max(r-l-w, 0LL);
        };
        const int R_bound = H - h + 1;
        const int C_bound = W - w + 1;
        lli remaining = W - w + 1;
        const function add = [&](int pos) {
                auto it = st.lower_bound(pos);
                int r = *it, l = *prev(it);
                remaining += gap(l, pos) + gap(pos, r) - gap(l, r);
                st.insert(pos);
        };
        const function del = [&](int pos) {
                auto it = st.find(pos);
                int r = *next(it), l = *prev(it);
                remaining -= gap(l, pos) + gap(pos, r) - gap(l, r);
                st.erase(it);
        };
        lli ans = (lli) (H - h + 1) * (W - w + 1);
        int i = 0;
        int start_from = 0;
        while(i < 2*N) {
                const int r = events[i][0];
                const int r_bounded = min(r, R_bound);
                if (start_from < r_bounded) {
                        ans -= (r_bounded - start_from) * (C_bound - remaining);
                        start_from = r_bounded;
                }
                while (i < 2*N and events[i][0] == r) {
                        const auto &[_, c, in_out] = events[i];
                        if (in_out == +1) add(c);
                        else              del(c);
                        i++;
                }
        }
        if (start_from < R_bound) ans -= (R_bound - start_from) * (C_bound - remaining);
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
