/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73927320
 * Link: https://atcoder.jp/contests/abc448/tasks/abc448_c
 */

#include <functional>
#include <iostream>
#include <map>
#include <set>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N, Q; cin >> N >> Q;
        vector<int> as(N);
        map<int, int> freq;
        set<int> st;
        for (auto &a : as) {
                cin >> a;
                st.insert(a);
                ++freq[a];
        }
        while (Q-->0) {
                int K; cin >> K;
                vector<int> bs(K);
                for (auto &b : bs) cin >> b;
                for (const auto &b : bs) {
                        if (--freq[as[b-1]] == 0) st.erase(as[b-1]);
                }
                cout << *st.begin() << '\n';
                for (const auto &b : bs) {
                        if (freq[as[b-1]]++ == 0) st.insert(as[b-1]);
                }
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
