/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75268206
 * Link: https://atcoder.jp/contests/abc455/tasks/abc455_d
 */

#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int N, Q;
        cin >> N >> Q;
        vector<int> nxt(N, -1);
        vector<int> v(N);
        for (int _ = 0; _ < Q; _++) {
                int C, P;
                cin >> C >> P;
                C--;
                P--;
                nxt[C] = P;
        }
        vector<int> ans(N, 0);
        vector<bool> visited(N, 0);
        for (int i = 0; i < N; i++) {
                if (!visited[i]) {
                        int k = i;
                        int cnt = 1;
                        while (nxt[k] != -1) {
                                visited[k] = 1;
                                cnt++;
                                k = nxt[k];
                        }
                        visited[k] = 1;
                        ans[k] = cnt;
                }
        }
        printv(ans);
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}
