/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75248172
 * Link: https://atcoder.jp/contests/abc455/tasks/abc455_b
 */

#include <functional>
#include <iostream>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int H, W;
        cin >> H >> W;
        vector<string> grid(H);
        for (auto & s : grid) {
                cin >> s;
        }

        const auto sym = [&](int h1, int w1, int h2, int w2) -> int {
                for (int i = h1; i <= h2; i++) {
                        for (int j = w1; j <= w2; j++) {
                                if (grid[i][j] != grid[h1+h2-i][w1+w2-j]) {
                                        return 0;
                                }
                        }
                }
                return 1;
        };

        lli ans = 0;
        for (int i = 0; i < H; i++) {
                for (int h = 0; h + i < H; h++) {
                        for (int j = 0; j < W; j++) {
                                for (int w = 0; w + j < W; w++) {
                                        ans += sym(i, j, i+h, j+w);
                                }
                        }
                }
        }
        cout << ans << '\n';
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}
