/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74513090
 * Link: https://atcoder.jp/contests/abc451/tasks/abc451_d
 */

#include <algorithm>
#include <cmath>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<int> two_pows;
        for (lli x = 1; x <= 1e9; x <<= 1) { two_pows.eb(x); }
        const function numlen = [](int x)->int {
                int res = 0;
                while (x) { res++; x /= 10; }
                return res;
        };
        vector<int> g;
        const function<void(lli)> f = [&](lli x) -> void {
                for (const int s : two_pows) {
                        lli t = x * pow(10, numlen(s)) + s;
                        if (t > 1e9) break;
                        f(t);
                        g.eb(t);
                }
        };
        f(0);
        sort(ALL(g));
        g.erase(unique(ALL(g)), g.end());
        // printv(g);
        cout << g[N-1] << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
