/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74505909
 * Link: https://atcoder.jp/contests/abc451/tasks/abc451_c
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define F first
#define S second

using namespace std;
using lli = long long int;

enum TagType { ADD, SET, NONE };
 
struct Tag {
        TagType type = NONE;
        lli val = 0;
};
 
struct LazySegTree {
        const int N;
        vector<lli> t;
        vector<Tag> tag;
 
        void build(int id, int l, int r) {
                if (l == r) {
                        t[id] = 0;
                } else {
                        int m = (l + r) / 2;
                        build(2*id, l, m);
                        build(2*id+1, m+1, r);
                        t[id] = t[2*id] + t[2*id+1];
                }
        }
 
        void apply(int id, int len, const Tag &x) {
                if (x.type == ADD) {
                        if (tag[id].type != SET) {
                                tag[id] = Tag{ADD, tag[id].val + x.val};
                        } else {
                                tag[id] = Tag{SET, tag[id].val + x.val};
                        }
                        t[id] += x.val * len;
                } else if (x.type == SET) {
                        t[id] = x.val * len;
                        tag[id] = x;
                }
        }
 
        void push_down(int id, int l, int r) {
                int m = (l + r) / 2;
                apply(2*id, m-l+1, tag[id]);
                apply(2*id+1, r-m, tag[id]);
                tag[id] = Tag();
        }
 
        void range_update(int id, int l, int r, int ql, int qr, const Tag &x) {
                if (qr < l or ql > r) return;
                if (ql <= l and r <= qr) {
                        apply(id, r-l+1, x);
                } else {
                        push_down(id, l, r);
                        int m = (l + r) / 2;
                        range_update(2*id, l, m, ql, qr, x);
                        range_update(2*id+1, m+1, r, ql, qr, x);
                        t[id] = t[2*id] + t[2*id+1];
                }
        }
 
        lli query_range_sum(int id, int l, int r, int ql, int qr) {
                if (qr < l or ql > r) return 0;
                if (l >= ql and r <= qr) return t[id];
                push_down(id, l, r);
                int m = (l + r) / 2;
                return query_range_sum(2*id, l, m, ql, qr) + query_range_sum(2*id+1, m+1, r, ql, qr);
        }
 
        LazySegTree(int _N) : N(_N), t(4*N), tag(4*N) {
                build(1, 0, N-1);
        }
};

void solution() {
        int Q; cin >> Q;
        vector<int> nums;
        vector<pair<int, int>> qs(Q);
        for (int i = 0; i < Q; i++) {
                cin >> qs[i].F >> qs[i].S;
                nums.eb(qs[i].S);
        }
        sort(ALL(nums));
        nums.erase(unique(ALL(nums)), nums.end());
        const function c = [&](int h) -> int {
                return lower_bound(ALL(nums), h) - nums.begin();
        };
        int N = SZ(nums);
        LazySegTree seg(N+10);
        for (const auto &[op, h] : qs) {
                int x = c(h);
                if (op == 1) {
                        seg.range_update(1, 0, N-1, x, x, Tag{ ADD, 1 });
                } else {
                        seg.range_update(1, 0, N-1, 0, x, Tag{ SET, 0 });
                }
                cout << seg.query_range_sum(1, 0, N-1, 0, N-1) << '\n';
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
