/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75068900
 * Link: https://atcoder.jp/contests/abc454/tasks/abc454_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <string>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        string A, B; cin >> A >> B;
        const auto f = [&](string &s) -> vector<char> {
                vector<char> stk;
                for (const char c : s) {
                        if (c == ')') {
                                if (SZ(stk) >= 3 and stk.end()[-3] == '(' and stk.end()[-2] == 'x' and stk.end()[-1] == 'x') {
                                        stk.pop_back();
                                        stk.pop_back();
                                        stk.pop_back();
                                        stk.push_back('x');
                                        stk.push_back('x');
                                } else {
                                        stk.push_back(')');
                                }
                        } else {
                                stk.push_back(c);
                        }
                }
                return stk;
        };
        auto resA = f(A), resB = f(B);
        if (SZ(resA) != SZ(resB)) {
                cout << "No\n";
                return;
        }
        for (int i = 0; i < SZ(resA); i++) {
                if (resA[i] != resB[i]) {
                        cout << "No\n";
                        return;
                }
        }
        cout << "Yes\n";
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        int T; cin >> T;
        while (T--)
                solution();
        return 0;
}
