# This file was auto-generated by UpCode
# Submission ID: 76026587
# Link: https://atcoder.jp/contests/abc459/tasks/abc459_a

X = int(input())
X -= 1
for i, c in enumerate("HelloWorld"):
    if (i != X): print(c, end='')
