/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 76037995
 * Link: https://atcoder.jp/contests/abc459/tasks/abc459_b
 */

#include <iostream>
#include <map>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

#define X(a, b) if (a <= c and c <= b)

int C(char c) {
        if ('p' <= c and c <= 's') return 7;
        if ('t' <= c and c <= 'v') return 8;
        if ('w' <= c and c <= 'z') return 9;
        return 2 + (c - 'a') / 3;
}

void solution() {
        int N;
        cin >> N;
        string s = "";
        for (int _ = 0; _ < N; _++) {
                string t;
                cin >> t;
                s += C(t[0]) + '0';
        }
        cout << s << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
