/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 73947067
 * Link: https://atcoder.jp/contests/abc448/tasks/abc448_f
 */

#include <algorithm>
#include <cmath>
#include <iostream>
#include <numeric>
#include <vector>

using namespace std;

int main() {
	cin.tie(0)->sync_with_stdio(0);
	int N; cin >> N;
	vector<int> xs(N), ys(N);
	for (int i = 0; i < N; i++) cin >> xs[i] >> ys[i];
	int B = 2e7 / sqrt(N);
	vector<int> ord(N);
	iota(ord.begin(), ord.end(), 0);
	sort(ord.begin(), ord.end(), [&](int a, int b) {
		if (xs[a] / B != xs[b] / B) return xs[a] / B < xs[b] / B;
		if ((xs[a] / B) % 2 == 1)   return ys[a] > ys[b];
		else                        return ys[a] < ys[b];
	});
	auto it = ord.begin();
	while (*it != 0) ++it;
	rotate(ord.begin(), it, ord.end());
	for (int i = 0; i < N; i++)
		cout << ord[i] + 1 << " \n"[i==N-1];
	return 0;
}
