/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74813615
 * Link: https://atcoder.jp/contests/abc438/tasks/abc438_c
 */

#include <algorithm>
#include <cinttypes>
#include <functional>
#include <iostream>
#include <set>
#include <tuple>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<int> A(N);
        for (auto &a : A) cin >> a;
        vector<int> stk;
        int ans = N;
        for (int i = 0; i < N; i++) {
                stk.eb(A[i]);
                const auto cmp = [&]() -> bool {
                        for (int i = -4; i <= -2; i++) if (stk.end()[i] != stk.end()[i+1]) return 0;
                        return 1;
                };
                while (SZ(stk) >= 4 and cmp()) {
                        stk.pop_back(); stk.pop_back(); stk.pop_back(); stk.pop_back();
                        ans -= 4;
                }
        }
        cout << ans << '\n';

}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
