/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74513400
 * Link: https://atcoder.jp/contests/abc451/tasks/abc451_b
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; \
    ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); \
    cerr << '\n'; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; \
    int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; \
    cerr << "]\n"; } while(0)
#define printv(x) \
    { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N, M; cin >> N >> M;
        vector<int> v(M+1, 0);
        for (int i = 0; i < N; i++) {
                int A, B; cin >> A >> B;
                v[A]--; v[B]++;
        }
        for (int i = 1; i <= M; i++) {
                cout << v[i] << '\n';
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
