/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74131693
 * Link: https://atcoder.jp/contests/abc449/tasks/abc449_c
 */

#include <iostream>
#include <map>
#include <string>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N, L, R; cin >> N >> L >> R;
        string S; cin >> S;
        map<char, int> cnt;
        lli ans = 0;
        for (int j = 0; j <= SZ(S); j++) {
                if (j-R-1 >= 0) cnt[S[j-R-1]]--;
                if (j-L   >= 0) cnt[S[j-L  ]]++;
                ans += cnt[S[j]];
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
