/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75024092
 * Link: https://atcoder.jp/contests/abc416/tasks/abc416_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

constexpr lli INF = 1e18;

void solution() {
        int N, M; cin >> N >> M;
        int sky = N+1;
        vector<vector<lli>> dist(N+2, vector<lli> (N+2, INF));
        for (int i = 1; i <= N+1; i++) dist[i][i] = 0;
        while (M--) {
                int x, y; lli t; cin >> x >> y >> t;
                dist[x][y] = min(t, dist[x][y]);
                dist[y][x] = min(t, dist[y][x]);
        }
        int K, T; cin >> K >> T;
        while (K--) {
                int x; cin >> x;
                dist[x][sky] = T;
                dist[sky][x] = 0;
        }

        for (int k = 1; k <= N+1; k++) {
                for (int i = 1; i <= N+1; i++) {
                        for (int j = 1; j <= N+1; j++) {
                                dist[i][j] = min(dist[i][k]+dist[k][j], dist[i][j]);
                        }
                }
        }

        lli ans = 0;
        for (int i = 1; i <= N; i++) {
                for (int j = 1; j <= N; j++) {
                        if (dist[i][j] == INF) continue;
                        ans += dist[i][j];
                }
        }

        int Q; cin >> Q;
        while (Q--) {
                int type; cin >> type;
                if (type == 1) {
                        int x, y; lli t; cin >> x >> y >> t;
                        for (int i = 1; i <= N+1; i++) {
                                for (int j = 1; j <= N+1; j++) {
                                        if (dist[i][j] > dist[i][x] + t + dist[y][j]) {
                                                if (i != sky and j != sky) {
                                                        if (dist[i][j] != INF) ans -= dist[i][j];
                                                        ans += dist[i][x] + t + dist[y][j];
                                                }
                                                dist[i][j] = dist[i][x] + t + dist[y][j];
                                        }
                                        if (dist[i][j] > dist[i][y] + t + dist[x][j]) {
                                                if (i != sky and j != sky) {
                                                        if (dist[i][j] != INF) ans -= dist[i][j];
                                                        ans += dist[i][y] + t + dist[x][j];
                                                }
                                                dist[i][j] = dist[i][y] + t + dist[x][j];
                                        }
                                }
                        }
                } else if (type == 2) {
                        int x; cin >> x;
                        for (int i = 1; i <= N+1; i++) {
                                for (int j = 1; j <= N+1; j++) {
                                        if (dist[i][j] > dist[i][x] + T + dist[sky][j]) {
                                                if (i != sky and j != sky) {
                                                        if (dist[i][j] != INF) ans -= dist[i][j];
                                                        ans += dist[i][x] + T + dist[sky][j];
                                                }
                                                dist[i][j] = dist[i][x] + T + dist[sky][j];
                                        }
                                        if (dist[i][j] > dist[i][sky] + dist[x][j]) {
                                                if (i != sky and j != sky) {
                                                        if (dist[i][j] != INF) ans -= dist[i][j];
                                                        ans += dist[i][sky] + dist[x][j];
                                                }
                                                dist[i][j] = dist[i][sky] + dist[x][j];
                                        }
                                }
                        }
                } else {
                        cout << ans << '\n';
                }
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
