/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75101197
 * Link: https://atcoder.jp/contests/abc454/tasks/abc454_e
 */

#include <functional>
#include <iostream>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int N, A, B; cin >> N >> A >> B;
        A--; B--;
        if (N % 2 == 1 or (A + B)  % 2 == 0) {
                cout << "No\n";
                return;
        }
        string s = "";
        for (int i = 0; i+2 <= A; i += 2) {
                s += string(N-1, 'R') + "D" + string(N-1, 'L') + "D";
        }
        for (int j = 0; j+2 <= B; j += 2) {
                s += "DRUR";
        }
        if (A % 2 == 0 and B % 2 == 1) {
                s += "DR";
        } else { // A % 2 == 1 and B % 2 == 0
                s += "RD";
        }
        for (int j = B-(B%2); j+2 < N; j += 2) {
                s += "RURD";
        }
        for (int i = A-(A%2); i+2 < N; i += 2) {
                s += "D" + string(N-1, 'L') + "D" + string(N-1, 'R');
        }
        cout << "Yes\n";
        cout << s << '\n';
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        int T; cin >> T;
        while(T--) solution();
        return 0;
}
