/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 76051272
 * Link: https://atcoder.jp/contests/abc459/tasks/abc459_c
 */

#include <atcoder/fenwicktree>
#include <atcoder/segtree>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

int e() {
        return 1e6;
}

int op(int a, int b) {
        return min(a, b);
}

void solution() {
        int N;
        cin >> N;
        atcoder::segtree<int, op, e> seg(vector<int> (N, 0));
        int Q;
        cin >> Q;
        atcoder::fenwick_tree<int> fwt(6e5 + 1);
        fwt.add(0, N);
        for (int _ = 0; _ < Q; _++) {
                int t, x;
                cin >> t >> x;
                if (t == 1) {
                        int val = seg.get(x-1);
                        fwt.add(val, -1);
                        fwt.add(val+1, 1);
                        seg.set(x-1, val+1);
                } else {
                        cout << fwt.sum(x+seg.all_prod(), 6e5 + 1) << '\n';
                }
                test(seg.all_prod());
        }
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
