/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75491073
 * Link: https://atcoder.jp/contests/abc453/tasks/abc453_g
 */

#include <cassert>
#include <cstdint>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using i64 = int64_t;
using i32 = int32_t;
using namespace std;

class PersistentSegTree {
    private:
        struct S {
                i64 sum = 0;
                int l = -1, r = -1;
        };

        vector<S> t;
        int N;
        int timer = 1;

        S op(int l, int r) { return S{t[l].sum + t[r].sum, l, r}; }

        int build(int tl, int tr) {
                if (tl == tr) {
                        t[timer] = {0, -1, -1};
                        return timer++;
                }

                int mid = (tl + tr) / 2;
                t[timer] = op(build(tl, mid), build(mid+1, tr));

                return timer++;
        }

        int set(int id, int pos, int val, int tl, int tr) {
                assert(id != -1);
                if (tl == tr) {
                        t[timer] = {val, 0, 0};
                        return timer++;
                }

                int mid = (tl + tr) / 2;
                if (pos <= mid) {
                        t[timer] = op(set(t[id].l, pos, val, tl, mid), t[id].r);
                } else {
                        t[timer] = op(t[id].l, set(t[id].r, pos, val, mid+1, tr));
                }

                return timer++;
        }

        i64 prod(int id, int ql, int qr, int tl, int tr) {
                assert(id != -1);
                if (qr < tl or tr < ql) {
                        return 0LL;
                }

                if (ql <= tl and tr <= qr) {
                        return t[id].sum;
                }

                int mid = (tl + tr) / 2;
                return prod(t[id].l, ql, qr, tl, mid) + prod(t[id].r, ql, qr, mid+1, tr);
        }

    public:
        PersistentSegTree(int N, int MAXN) : t(MAXN), N(N) {}
        int build() { return build(0, N-1); }
        int set(int root, int pos, i64 val) { return set(root, pos, val, 0, N-1); }
        i64 prod(int root, int l, int r) { return prod(root, l, r, 0, N-1); }

        int add_copy(int root) {
                t[timer] = t[root];
                return timer++;
        }
};

void solution() {
        int N, M, Q;
        cin >> N >> M >> Q;

        PersistentSegTree st(M, 4*M+Q*(2+__lg(M)));
        int zero_root = st.build();
        vector<int> roots(N, zero_root);

        for (int _ = 0; _ < Q; _++) {
                int op;
                cin >> op;

                if (op == 1) {
                        int X, Y;
                        cin >> X >> Y;
                        X--;
                        Y--;
                        roots[X] = roots[Y];
                }
                if (op == 2) {
                        int X, Y, Z;
                        cin >> X >> Y >> Z;
                        X--;
                        Y--;
                        roots[X] = st.set(roots[X], Y, Z);
                }
                if (op == 3) {
                        int X, L, R;
                        cin >> X >> L >> R;
                        X--;
                        L--;
                        R--;
                        cout << st.prod(roots[X], L, R) << '\n';
                }
        }
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
