/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74535065
 * Link: https://atcoder.jp/contests/abc451/tasks/abc451_f
 */

#pragma GCC target("popcnt")
#include <algorithm>
#include <atcoder/dsu>
#include <functional>
#include <iostream>
#include <set>
#include <utility>
#include <vector>
#ifndef ONLINE_JUDGE
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

bool exist_in_set(set<int> &A, int x) {
        return A.find(x) != A.end();
}

void union_sets(set<int> &A, set<int> &B) {
        for (const int &x : B) {
                if (not exist_in_set(A, x)) {
                        A.insert(x);
                }
        }
}

void solution() {
        int N, Q; cin >> N >> Q;
        vector C(2, vector<set<int>> (N+1));
        atcoder::dsu dsu(N+1);
        int ans = 0;
        for (int i = 1; i <= N; i++) C[0][i].insert(i);
        while (Q-->0) {
                int u, v; cin >> u >> v;
                if (ans == -1) {
                        cout << -1 << '\n';
                        continue;
                }
                int lu = dsu.leader(u), lv = dsu.leader(v);
                bool diff = exist_in_set(C[0][lu], u) ^ exist_in_set(C[0][lv], v);
                if (dsu.same(u, v)) {
                        if (diff == 0) {
                                ans = -1;
                        }
                } else {
                        if (dsu.size(u) < dsu.size(v)) {
                                swap(u, v);
                                swap(lu, lv);
                        }

                        ans -= min(SZ(C[0][lu]), SZ(C[1][lu]));
                        ans -= min(SZ(C[0][lv]), SZ(C[1][lv]));

                        if (diff) {
                                union_sets(C[0][lu], C[0][lv]);
                                union_sets(C[1][lu], C[1][lv]);
                        } else {
                                union_sets(C[0][lu], C[1][lv]);
                                union_sets(C[1][lu], C[0][lv]);
                        }
                        C[0][lv] = C[1][lv] = set<int>();
                        int nl = dsu.merge(lu, lv);
                        if (nl != lu) {
                                C[0][nl] = C[0][lu];
                                C[1][nl] = C[1][lu];
                                C[0][lu] = C[1][lu] = set<int>();
                        }

                        ans += min(SZ(C[0][nl]), SZ(C[1][nl]));
                }

                cout << ans << '\n';
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
