/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75678917
 * Link: https://atcoder.jp/contests/abc457/tasks/abc457_e
 */

#include <algorithm>
#include <cstdint>
#include <functional>
#include <iostream>
#include <vector>
#include <set>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

struct SegTree {
        vector<int> t;

        void build(int id, int tl, int tr, vector<multiset<int>> &st) {
                if (tl == tr) {
                        if (!st[tl].empty()) t[id] = *st[tl].begin();
                        else t[id] = 2e5 + 10;
                        return;
                }
                int tm = (tl + tr) / 2;
                build(2*id, tl, tm, st);
                build(2*id+1, tm+1, tr, st);
                t[id] = min(t[2*id], t[2*id+1]);
        }

        int query(int id, int tl, int tr, int ql, int qr) {
                if (ql > tr or qr < tl) return 2e5 + 10;
                if (ql <= tl and tr <= qr) return t[id];
                int tm = (tl + tr) / 2;
                if (qr <= tm) return query(2*id, tl, tm, ql, qr);
                else if (ql > tm) return query(2*id+1, tm+1, tr, ql, qr);
                else return min(query(2*id, tl, tm, ql, qr), query(2*id+1, tm+1, tr, ql, qr));
        }

        SegTree(int _MAXN): t(_MAXN) {}
};

void solution() {
        int N, M;
        cin >> N >> M;
        vector<multiset<int>> st(N+1), ed(N+1);
        for (int _ = 0; _ < M; _++) {
                int L, R;
                cin >> L >> R;
                st[L].insert(R);
                ed[R].insert(L);
        }
        SegTree seg(4 * N + 10);
        seg.build(1, 1, N, st);
        int Q;
        cin >> Q;
        for (int _ = 0; _ < Q; _++) {
                int S, T;
                cin >> S >> T;
                if (st[S].empty() or ed[T].empty()) {
                        cout << "No\n";
                } else if (S == T) {
                        auto it = st[S].lower_bound(T);
                        ++it;
                        if (it != st[S].end() and *it == T) {
                                cout << "Yes\n";
                        } else {
                                cout << "No\n";
                        }
                } else if (st[S].find(T) != st[S].end()) {
                        auto it = st[S].lower_bound(T);
                        ++it;
                        if (it != st[S].end() and *it == T) {
                                cout << "Yes\n";
                        } else {
                                --it;
                                if (it == st[S].begin()) {
                                        int x = seg.query(1, 1, N, S+1, T);
                                        if (x <= T) {
                                                cout << "Yes\n";
                                        } else {
                                                if (ed[T].upper_bound(S) != ed[T].end()) {
                                                        cout << "Yes\n";
                                                } else {
                                                        cout << "No\n";
                                                }
                                        }
                                } else {
                                        cout << "Yes\n";
                                }
                        }
                } else {
                        auto it1 = st[S].upper_bound(T), it2 = ed[T].upper_bound(S);
                        if (it1 != st[S].begin() and it2 != ed[T].end() and *(--it1) + 1 >= *(it2)) {
                                cout << "Yes\n";
                        } else {
                                cout << "No\n";
                        }
                }
        }
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
