/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74725441
 * Link: https://atcoder.jp/contests/abc436/tasks/abc436_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<int> P(N+1);
        for (int i = 1; i <= N; i++) {
                cin >> P[i];
        }
        vector<bool> visited(N+1, 0);
        lli K = 0;
        const function<void(int, int)> dfs = [&](int cur, lli cycle_sz) -> void {
                if (visited[cur]) {
                        K += (cycle_sz) * (cycle_sz - 1) / 2;
                        return;
                }
                visited[cur] = 1;
                dfs(P[cur], cycle_sz + 1);
        };
        for (int i = 1; i <= N; i++) {
                if (not visited[i]) dfs(i, 0);
        }
        cout << K << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
