/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74292916
 * Link: https://atcoder.jp/contests/abc450/tasks/abc450_d
 */

#include <algorithm>
#include <iostream>
#include <functional>
#include <set>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N; lli K; cin >> N >> K;
        vector<lli> A(N);
        for (int i = 0; i < N; i++) {
                cin >> A[i];
                A[i] %= K;
        }
        sort(ALL(A));
        lli minVal = A[0];
        for (int i = 0; i < N; i++)
                A[i] -= minVal;
        lli maxVal = A[N-1];
        lli ans = maxVal;
        for (int i = 0; i < N-1; i++) {
                ans = min(max(A[i]+K-maxVal, A[i]+K-A[i+1]), ans);
                // test(ans);
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
