/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 68134264
 * Link: https://atcoder.jp/contests/abc417/tasks/abc417_c
 */

#pragma GCC optimize("Ofast")
#include <iostream>
#include <map>
#define fastio cin.tie(0)->sync_with_stdio(false)
#define eb emplace_back
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x) { \
    for (auto i : x) cout << i << ' '; \
    cout << endl; \
}
#define pii pair<int, int>
#define pll pair<lli, lli>
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()
#define MP(x, y) make_pair((x), (y))
#define SQ(x) ((x)*(x))
#define SZ(x) ((int) x.size())

using namespace std;
typedef long long int lli;

template <typename A, typename B>
ostream& operator << (ostream& o, pair<A, B> a) {
    return o << a.first << ' ' << a.second;
}
template <typename A, typename B>
istream& operator >> (istream& o, pair<A, B> &a) {
    return o >> a.first >> a.second;
}

map<int, int> freq;

void solve() {
    int N; cin >> N;
    lli ans = 0;
    for (int i = 0; i < N; i++) {
        int Ai; cin >> Ai;
        ans += freq[i-Ai];
        freq[i+Ai]++;
    }
    cout << ans << '\n';
}

int main() {
    fastio;
    solve();
    return 0;
}