/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74804322
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_e
 */

#include <algorithm>
#include <cmath>
#include <functional>
#include <iostream>
#include <iomanip>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

struct point {
        double x = 0, y = 0;
        point operator-(const point &o) {
                return {x-o.x, y-o.y};
        }
        double norm() {
                return sqrt(SQ(x) + SQ(y));
        }
};

point internal_division(point &a, point &b, double p) {
        return {a.x + (b.x - a.x) * p,
                a.y + (b.y - a.y) * p};
}

constexpr int NUM_ITERATION = 67;

double dist_segment_and_origin(point a, point b) {
        const auto e = [&](double p) -> double {
                return (internal_division(a, b, p) - point{0, 0}).norm();
        };
        double l = 0, r = 1;
        for (int i = 0; i < NUM_ITERATION; i++) {
                double ml = (2*l + r) / 3;
                double mr = (l + 2*r) / 3;
                if (e(ml) < e(mr)) r = mr;
                else               l = ml;
        }
        return e(l);
}

void solution() {
        point ts, tg, as, ag;
        cin >> ts.x >> ts.y >> tg.x >> tg.y;
        cin >> as.x >> as.y >> ag.x >> ag.y;
        if ((ts-tg).norm() < (as-ag).norm()) {
                swap(ts, as);
                swap(tg, ag);
        }
        point tm = internal_division(ts, tg, (as-ag).norm() / (ts-tg).norm());
        double d1 = dist_segment_and_origin(ts-as, tm-ag);
        double d2 = dist_segment_and_origin(tm-ag, tg-ag);
        cout << min(d1, d2) << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        int T; cin >> T;
        cout << fixed << setprecision(15);
        while(T--)
                solution();
        return 0;
}
