/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75374687
 * Link: https://atcoder.jp/contests/abc455/tasks/abc455_f
 */

#include <atcoder/lazysegtree.hpp>
#include <atcoder/modint>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;
using mint = atcoder::modint998244353;

namespace st {
        struct S {
                mint cnt, sum, sumsq;
        };

        S e() {
                return S(1, 0, 0);
        }

        S op(S a, S b) {
                return S(a.cnt+b.cnt, a.sum+b.sum, a.sumsq+b.sumsq);
        }

        S mapping(mint f, S x) {
                x.sumsq += 2*x.sum*f + x.cnt*f*f;
                x.sum += f * x.cnt;
                return x;
        }

        mint composition(mint f, mint g) {
                return f+g;
        }

        mint id() {
                return 0;
        }
}

void solution() {
        int N, Q;
        cin >> N >> Q;
        atcoder::lazy_segtree<st::S, st::op, st::e, mint, st::mapping, st::composition, st::id> t(N);
        for (int _ = 0; _ < Q; _++) {
                int l, r, a;
                cin >> l >> r >> a;
                l--;
                t.apply(l, r, mint(a));
                st::S s = t.prod(l, r);
                mint ans = (s.sum * s.sum - s.sumsq) / 2;
                cout << ans.val() << '\n';
        }
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}