/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74811988
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <string>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; string S; cin >> N >> S;
        vector<int> max_len(2, 0), cnt(2, 0);
        int l = 0;
        while (l < N) {
                int r = l + 1;
                while(r < N and S[l] == S[r]) r++;
                int c = S[l] - '0';
                int len = r - l;
                max_len[c] = max(max_len[c], len);
                cnt[c] += len;
                l = r;
        }
        cout << min((cnt[0] - max_len[0])*2 + (cnt[1]), (cnt[1] - max_len[1])*2 + (cnt[0])) << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        int T; cin >> T;
        while(T-->0)
                solution();
        return 0;
}
