/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74664926
 * Link: https://atcoder.jp/contests/abc452/tasks/abc452_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <string>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        string S, T; cin >> S >> T;
        int N = SZ(S), M = SZ(T);
        vector<int> dp(M+1, -1);
        lli ans = 0;
        dp[0] = 0;
        for (int i = 0; i < N; i++) {
                for (int j = M-1; j >= 0; j--) {
                        if (S[i] == T[j]) {
                                if (j == 0)
                                        dp[j+1] = i;
                                else
                                        dp[j+1] = dp[j];
                        }
                }
                testv(dp);
                ans += max(0, i-dp[M]);
                test(i, dp[M]);
        }
        cout << ans << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
