/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75275333
 * Link: https://atcoder.jp/contests/abc455/tasks/abc455_e
 */

#include <algorithm>
#include <array>
#include <functional>
#include <iostream>
#include <string>
#include <map>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using lli = long long int;
using namespace std;

void solution() {
        lli N;
        cin >> N;
        string S;
        cin >> S;
        int X = 0, Y = 0;
        map<int, int> mpab, mpac, mpbc;
        map<pair<int, int>, int> mpabc;
        lli res = 0;
        mpab[0] = 1;
        mpac[0] = 1;
        mpbc[0] = 1;
        mpabc[{0, 0}] = 1;
        for (int i = 0; i < N; i++) {
                if (S[i] == 'A') {
                        X++;
                        Y++;
                } else if (S[i] == 'B') {
                        Y--;
                } else {
                        X--;
                }
                res += mpab[X] + mpac[Y] + mpbc[Y-X] - 2*mpabc[{X, Y}];
                mpab[X]++;
                mpac[Y]++;
                mpbc[Y-X]++;
                mpabc[{X, Y}]++;
        }
        cout << ( N * (N + 1) / 2 ) - res << '\n';
}

int main() {
        ios_base::sync_with_stdio(false);
        cin.tie(nullptr);
        solution();
        return 0;
}
