/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74820954
 * Link: https://atcoder.jp/contests/abc417/tasks/abc417_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <map>
#include <tuple>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<tuple<int, int, int>> pab(N);
        for (auto &[p, a, b] : pab) cin >> p >> a >> b;
        // map<mood, indices of query>
        map<int, vector<int>> mp;
        int Q; cin >> Q;
        for (int i = 0; i < Q; i++) {
                int x; cin >> x;
                mp[x].eb(i);
        }

        int sum_of_b = 0;
        vector<pair<int, vector<int>>> stk;

        for (const auto &[p, a, b] : pab) {
                while (not mp.empty()) {
                        auto it = mp.begin();
                        auto [key, value] = *it;
                        if (key - sum_of_b > p) break;
                        mp.erase(it);
                        int new_key = max(key - sum_of_b, 0) + sum_of_b + a + b;
                        stk.eb(new_key, value);
                }
                while (not stk.empty()) {
                        auto [key, value] = stk.back();
                        stk.pop_back();
                        auto &vec = mp[key];
                        if (SZ(vec) < SZ(value)) swap(vec, value);
                        vec.insert(vec.end(), value.begin(), value.end());
                }
                sum_of_b += b;
        }
        vector<int> ans(Q);
        for (const auto &[key, value] : mp) {
                for (const int &idx : value) {
                        ans[idx] = max(0, key-sum_of_b);
                }
        }
        for (const int &v : ans) cout << v << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
