/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 68055049
 * Link: https://atcoder.jp/contests/abc416/tasks/abc416_d
 */

#pragma GCC optimize("Ofast")
#include <iostream>
#include <algorithm>
#include <vector>
#include <set>
#define fastio cin.tie(0)->sync_with_stdio(false)
#define eb emplace_back
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x) { \
    for (auto i : x) cout << i << ' '; \
    cout << endl; \
}
#define pii pair<int, int>
#define pll pair<lli, lli>
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()
#define MP(x, y) make_pair((x), (y))
#define SQ(x) ((x)*(x))
#define SZ(x) ((int) x.size())

using namespace std;
typedef long long int lli;

template <typename A, typename B>
ostream& operator << (ostream& o, pair<A, B> a) {
    return o << a.first << ' ' << a.second;
}
template <typename A, typename B>
istream& operator >> (istream& o, pair<A, B> &a) {
    return o >> a.first >> a.second;
}

const int inf = 1e9 + 7;

void solve() {
    int N, M;
    cin >> N >> M;
    vector<lli> As(N), Bs(N);
    lli Sa = 0, Sb = 0;
    for (auto &x : As) {
        cin >> x;
        Sa += x;
    }
    for (auto &x : Bs) {
        cin >> x;
        Sb += x;
    }
    sort(rALL(As));
    sort(ALL(Bs));
    int ib = 0;
    lli c = 0;
    for (auto x : As) {
        while (ib < N && x + Bs[ib] < M) ib++;
        if (ib < N && x + Bs[ib] >= M) {
            // cout << x << ' ' << Bs[ib] << endl;
            c++;
            ib++;
        }
    }
    cout << Sa + Sb - c * M << '\n';
}

int main() {
    fastio;
    int T; cin >> T;
    while (T--) solve();
    return 0;
}