/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75153756
 * Link: https://atcoder.jp/contests/abc452/tasks/abc452_c
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <set>
#include <string>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<int> A(N), B(N);
        for (int i = 0; i < N; i++) {
                cin >> A[i] >> B[i];
                B[i]--;
        }
        int M; cin >> M;
        vector<string> dict(M);
        for (auto &s : dict) cin >> s;
        vector spine(N, array<int, 26> {});
        for (int i = 0; i < M; i++) {
                for (int j = 0; j < N; j++) {
                        if (dict[i].size() != A[j]) continue;
                        spine[j][dict[i][B[j]]-'a'] = 1;
                }
        }
        for (int i = 0; i < M; i++) {
                bool ok = true;
                if (dict[i].size() == N) {
                        for (int j = 0; j < N; j++) {
                                if (!spine[j][dict[i][j]-'a']) {
                                        ok = false;
                                        break;
                                }
                        }
                } else {
                        ok = false;
                }
                cout << ( ok ? "Yes\n" : "No\n" );
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}