/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74140395
 * Link: https://atcoder.jp/contests/abc449/tasks/abc449_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()
#define F first
#define S second

using namespace std;
using lli = long long int;

constexpr lli INF = 1e18 + 2026;

struct BIT {
        int N;
        vector<int> b;
        BIT(int _N) : N(_N), b(_N+1, 0) {}
        int lowbit(int x) { return x & -x; }
        int qry(int i) { int s = 0; for (int j = i; j >= 1; j -= lowbit(j)) s += b[j]; return s; }
        void upd(int i, int d) { for (int j = i; j <= N; j += lowbit(j)) b[j] += d; }
        int lb(int w) { // find smallest i s.t. pre[i] >= w
                int l = 1, r = N;
                while (l < r) {
                        int m = (l + r) / 2;
                        if (qry(m) >= w) r = m;
                        else             l = m + 1;
                }
                return l;
        }
};


void solution() {
        int N, M; cin >> N >> M;
        vector<int> A(N+1), cnt(M+1, 0);
        for (int i = 1; i <= N; i++) { cin >> A[i]; cnt[A[i]]++; }
        vector<pair<int, int>> v;
        for (int i = 1; i <= M; i++) v.emplace_back(cnt[i], i);
        sort(v.begin(), v.end());
        vector<lli> len(M+1);
        len[0] = N;
        for (int i = 1; i < M; i++) len[i] = (lli)i * (v[i].F - v[i-1].F) + len[i-1];
        len[M] = INF;
        int Q; cin >> Q;
        vector<int> ans(Q);
        vector<tuple<int, int, int>> queries;
        for (int i = 0; i < Q; i++) {
                lli X; cin >> X;
                if (X <= N) { ans[i] = A[X]; continue; }
                int l = 1, r = M;
                while (l < r) {
                        int m = (l + r) / 2;
                        if (len[m] >= X) r = m;
                        else             l = m + 1;
                }
                int k = l;
                X -= len[k-1];
                X = (X - 1) % k + 1;
                queries.emplace_back(k, X, i);
        }
        sort(ALL(queries));
        BIT fw(M);
        int it = 0;
        for (auto [k, X, i] : queries) {
                while (it < k) { fw.upd(v[it].S, +1); it++; }
                ans[i] = fw.lb(X);
        }
        for (int i = 0; i < Q; i++) cout << ans[i] << '\n';
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
