/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 76091704
 * Link: https://atcoder.jp/contests/abc459/tasks/abc459_e
 */

#include <atcoder/modint>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define ALL(x) std::begin(x), std::end(x)
#define rALL(X) std::rbegin(x), std::rend(x)
#define SZ(x) ((int) x.size())
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

using mint = atcoder::modint998244353;

void solution() {
        int N;
        cin >> N;
        vector<int> D(N);
        vector<lli> C(N);
        vector<vector<int>> adj(N);
        for (int i = 1; i < N; i++) {
                int pi;
                cin >> pi;
                pi--;
                adj[pi].emplace_back(i);
        }
        for (auto &c : C) cin >> c;
        for (auto &d : D) cin >> d;

        mint ans = 1;

        const auto dfs = [&](this auto&& self, int cur) -> lli {
                lli s = C[cur];
                for (auto &nxt : adj[cur]) s += self(nxt);
                if (s < D[cur]) {
                        ans = 0;
                        return 0;
                }
                for (int i = 0; i < D[cur]; i++) {
                        // C(s, d)
                        ans *= (s - i);
                        ans /= (i + 1);
                }
                return s - D[cur];
        };

        dfs(0);
        cout << ans.val() << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
