/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75671631
 * Link: https://atcoder.jp/contests/abc457/tasks/abc457_d
 */

#include <algorithm>
#include <cstdint>
#include <cmath>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using i64 = int64_t;
using i32 = int32_t;
using namespace std;

void solution() {
        i32 N;
        i64 K;
        cin >> N >> K;
        vector<i64> A(N);
        i64 m = 1e18;
        for (auto &a : A) {
                cin >> a;
                m = min(m, a);
        }
        const auto check = [&](i64 val) -> bool {
                i64 _k = K;
                for (i64 i = 0; i < N; i++) if (val > A[i]) {
                        _k -= (val - A[i] + i) / (i + 1);
                        if (_k < 0) return false;
                }
                return true;
        };
        i64 L = m, R = 2e18 + 1;
        for (int _ = 0; _ < 67; _++) {
                i64 M = (L + R) >> 1;
                if (check(M)) L = M;
                else R = M;
        }
        if (check(L+1)) L++;
        const auto check2 = [&](i64 val) {
                for (int i = 0; i < N; i++) if (val >= A[i] and (val - A[i]) % (i + 1) == 0) return true;
                return false;
        };
        while (!check2(L)) L--;
        cout << L << '\n';
}

i32 main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
