/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74132235
 * Link: https://atcoder.jp/contests/abc449/tasks/abc449_b
 */

#include <iostream>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int H, W, Q; cin >> H >> W >> Q;
        while (Q-->0) {
                int t, x; cin >> t >> x;
                if (t == 1) {
                        cout << W * x << '\n';
                        H -= x;
                }
                if (t == 2) {
                        cout << H * x << '\n';
                        W -= x;
                }
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
