/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74981205
 * Link: https://atcoder.jp/contests/abc417/tasks/abc417_e
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N, M, X, Y; cin >> N >> M >> X >> Y;
        vector<vector<int>> adj(N+1);
        while (M--) {
                int u, v; cin >> u >> v;
                adj[u].eb(v);
                adj[v].eb(u);
        }
        for (int i = 1; i <= N; i++) sort(ALL(adj[i]));
        vector<bool> visited(N+1, 0);
        vector<int> path;
        const function<void(int)> dfs = [&](int cur) {
                path.eb(cur);
                visited[cur] = 1;
                if (cur == Y) return;
                for (const int &nxt : adj[cur]) if (path.back() != Y and not visited[nxt]) {
                        dfs(nxt);
                }
                if (path.back() != Y) path.pop_back();
        };
        dfs(X);
        printv(path);
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        int T; cin >> T;
        while(T--)
                solution();
        return 0;
}
