/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 69856725
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_b
 */

#include <iostream>
#include <string>
#define fastio cin.tie(0)->sync_with_stdio(false)
#define eb emplace_back
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x) { \
    for (auto i : x) cout << i << ' '; \
    cout << endl; \
}
#define pii pair<int, int>
#define pll pair<lli, lli>
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.rbegin(), x.rend()
#define MP(x, y) make_pair((x), (y))
#define SQ(x) ((x)*(x))
#define SZ(x) ((int) x.size())

using namespace std;
typedef long long int lli;

template <typename A, typename B>
ostream& operator << (ostream& o, pair<A, B> a) {
    return o << a.first << ' ' << a.second;
}
template <typename A, typename B>
istream& operator >> (istream& o, pair<A, B> &a) {
    return o >> a.first >> a.second;
}

void solve() {
    char c1 = 0, c2 = 0;
    int cnt1 = 0, cnt2 = 0;
    string s; cin >> s;
    for (const auto &c : s) {
        if (c1) {
            if (c == c1) {
                cnt1++;
            } else {
                c2 = c;
                cnt2++;
            }
        } else {
            c1 = c;
            cnt1++;
        }
    }
    if (cnt1 == 1) cout << c1;
    else cout << c2;
}

int main() {
    fastio;
    solve();
    return 0;
}