/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74794017
 * Link: https://atcoder.jp/contests/abc435/tasks/abc435_d
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

void solution() {
        int N, M; cin >> N >> M;
        vector<vector<int>> adj(N+1);
        vector<bool> black(N+1, 0);
        for (int i = 0; i < M; i++) {
                int x, y; cin >> x >> y;
                adj[y].eb(x);
        }
        const function<void(int)> dfs = [&](int cur) -> void {
                if (black[cur]) return;
                black[cur] = 1;
                for (const int &nxt : adj[cur]) dfs(nxt);
        };
        int Q; cin >> Q;
        while (Q-->0) {
                int op, v; cin >> op >> v;
                if (op == 1) {
                        dfs(v);
                } else {
                        cout << (black[v] ? "Yes\n" : "No\n");
                }
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
