/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74812799
 * Link: https://atcoder.jp/contests/abc426/tasks/abc426_f
 */

#include <algorithm>
#include <atcoder/fenwicktree>
#include <atcoder/lazysegtree>
#include <functional>
#include <iostream>
#include <utility>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define fst first
#define sec second

using namespace std;
using lli = long long int;

constexpr lli INF = 4e18;

namespace seg {
        lli op(lli a, lli b) { return min(a,b); }
        lli e() { return INF; }
        lli mapping(lli tag, lli val) { return tag + val; }
        lli composition(lli tag1, lli tag2) { return tag1 + tag2; }
        lli tag_e() { return 0; }
        bool g(lli x) { return x >= 0; }
}

void solution() {
        int N; cin >> N;
        vector<lli> A(N);
        for (auto &a : A) cin >> a;
        atcoder::lazy_segtree<lli, seg::op, seg::e, lli, seg::mapping, seg::composition, seg::tag_e> seg_min(A);
        atcoder::fenwick_tree<int> alive(N);
        for (int i = 0; i < N; i++) alive.add(i, 1);
        const auto is_alive = [&](int p) -> int {
                return alive.sum(p, p+1);
        };
        int Q; cin >> Q;
        while(Q--) {
                int l, r; lli k; cin >> l >> r >> k;
                l--;
                lli res = alive.sum(l, r) * k;
                seg_min.apply(l, r, -k);
                while (seg_min.prod(l, r) < 0) {
                        int pos = seg_min.max_right<seg::g>(l);
                        res += seg_min.get(pos); // seg.get(p) == -k
                        seg_min.set(pos, INF);
                        alive.add(pos, -1);
                }
                cout << res << '\n';
        }
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
