/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 74304472
 * Link: https://atcoder.jp/contests/abc450/tasks/abc450_b
 */

#include <iostream>
#include <vector>
#define test(x) cerr << "Line(" << __LINE__ << ") " #x << ' ' << x << endl
#define printv(x)                          \
{                                          \
        for (auto i : x) cout << i << ' '; \
        cout << endl;                      \
}
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) x.begin(), x.end()
#define rALL(x) x.begin(), x.end()

using namespace std;
using lli = long long int;

void solution() {
        int N; cin >> N;
        vector<vector<int>> C(N, vector<int>(N));
        for (int i = 0; i < N-1; i++) for (int j = i+1; j < N; j++) cin >> C[i][j];
        for (int a = 0; a < N-2; a++) for (int b = a+1; b < N-1; b++) for (int c = b+1; c < N; c++) if (C[a][b] + C[b][c] < C[a][c]) { cout << "Yes\n"; return; }
        cout << "No\n";
}

int main() {
        cin.tie(nullptr)->sync_with_stdio(false);
        solution();
        return 0;
}
