/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75204957
 * Link: https://atcoder.jp/contests/dp/tasks/dp_g
 */

#include <algorithm>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

void solution() {
        int N, M;
        cin >> N >> M;

        vector<vector<int>> al(N+1);
        for (int _ = 0; _ < M; _++) {
                int x, y;
                cin >> x >> y;
                al[y].eb(x);
        }

        vector<int> dp(N+1, -1);

        const auto dfs = [&](this auto&& self, int cur) -> int {
                if (dp[cur] != -1)
                        return dp[cur];

                dp[cur] = 0;
                for (const auto &nxt : al[cur])
                        dp[cur] = max(self(nxt) + 1, dp[cur]);
                return dp[cur];
        };

        int ans = 0;
        for (int i = 1; i <= N; i++) {
                if (dp[i] == -1) {
                        ans = max(dfs(i), ans);
                }
        }
        cout << ans << '\n';
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}
