/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75205209
 * Link: https://atcoder.jp/contests/dp/tasks/dp_h
 */

#include <atcoder/modint>
#include <functional>
#include <iostream>
#include <string>
#include <vector>
#ifdef LOCAL
#define test(...) do { cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((cerr << ' ' << args), ...); }(__VA_ARGS__)); cerr << endl; } while(0)
#define testv(x) do { cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) cerr << (_i++ ? ", " : "") << _e; cerr << "]" << endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define printv(x) { for (auto i : (x)) cout << i << ' '; cout << endl; }
#define printlnv(x) { for (auto i : (x)) cout << i << '\n'; }
#define SQ(x) ((x) * (x))
#define SZ(x) ((int)x.size())
#define eb emplace_back
#define ALL(x) begin(x), end(x)
#define rALL(x) rbegin(x), rend(x)
#define CORDCOMP(x, fx) sort(ALL(x)); x.erase(unique(ALL(x)), end(x)); const auto fx = [&](int val) -> int { return lower_bound(ALL(x), val) - begin(x); }

using namespace std;
using lli = long long int;

using mint = atcoder::modint1000000007;

void solution() {
        int H, W;
        cin >> H >> W;
        vector<vector<mint>> dp(H+1, vector<mint> (W+1, 0));
        for (int i = 1; i <= H; i++) {
                string s;
                cin >> s;
                for (int j = 1; j <= W; j++) {
                        if (i == 1 and j == 1) {
                                dp[1][1] = 1;
                        } else if (s[j-1] == '#') {
                                dp[i][j] = 0;
                        } else {
                                dp[i][j] = dp[i-1][j] + dp[i][j-1];
                        }
                }
        }
        cout << dp[H][W].val() << '\n';
}

int main() {
        ios_base::sync_with_stdio(false); cin.tie(nullptr);
        solution();
        return 0;
}
