/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75605657
 * Link: https://atcoder.jp/contests/dp/tasks/dp_i
 */

#include <cstdint>
#include <functional>
#include <iostream>
#include <iomanip>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using i64 = int64_t;
using i32 = int32_t;
using namespace std;

void solution() {
        int N;
        cin >> N;
        vector<vector<double>> dp(N+1, vector<double> (N+1, 0));
        vector<double> p(N+1);
        for (int i = 1; i <= N; i++) {
                cin >> p[i];
        }
        dp[0][1] = 1 - p[1];
        dp[1][1] = p[1];
        for (int i = 0; i <= N; i++) {
                for (int j = 1; j <= N; j++) {
                        if (i > 0) {
                                dp[i][j] += dp[i-1][j-1] * p[j];
                        }
                        dp[i][j] += dp[i][j-1] * (1 - p[j]);
                }
        }
        double ans = 0;
        for (int i = N/2 + 1; i <= N; i++) {
                ans += dp[i][N];
        }
        cout << fixed << setprecision(10) << ans << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}