/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75679326
 * Link: https://atcoder.jp/contests/dp/tasks/dp_k
 */

#include <cstdint>
#include <functional>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

void solution() {
        int N, K;
        cin >> N >> K;

        vector<int> dp(K+1, 0);
        vector<int> a(N);
        for (int i = 0; i < N; i++) {
                cin >> a[i];
        }

        for (int i = 1; i <= K; i++) {
                for (int j = 0; j < N; j++) {
                        if (i - a[j] >= 0) {
                                if (dp[i - a[j]] == 0) dp[i] = 1;
                        }
                }
        }

        cout << (dp[K] ? "First" : "Second") << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}