/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75789479
 * Link: https://atcoder.jp/contests/dp/tasks/dp_l
 */

#include <algorithm>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

constexpr lli INF = 1e18;

void solution() {
        int N;
        cin >> N;
        vector<lli> A(N);
        for (auto &a : A) cin >> a;

        vector dp(N+1, vector<lli> (N+1, -INF));

        const auto dfs = [&](this auto &&self, int l, int r) -> lli {
                if (dp[l][r] != -INF) return dp[l][r];
                if (l == r) return dp[l][r] = 0;

                return dp[l][r] = max(-self(l+1, r) + A[l], -self(l, r-1) + A[r-1]);
        };

        cout << dfs(0, N) << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
