/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75798437
 * Link: https://atcoder.jp/contests/dp/tasks/dp_o
 */

#include <atcoder/modint>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

constexpr int MOD = 1e9 + 7;
constexpr int INF = MOD + 10;

void solution() {
        int N;
        cin >> N;
        vector<vector<int>> A(N, vector<int> (N));
        for (int i = 0; i < N; i++) for (int j = 0; j < N; j++) cin >> A[i][j];

        int mx = 1 << N;
        vector<lli> dp(mx, INF);

        const auto f = [&](this auto &&self, int mask) -> lli {
                if (mask == 0) return 1;
                if (dp[mask] != INF) return dp[mask];

                int k = 0;
                for (int i = 0; i < N; i++) if (mask & (1 << i)) k++;

                dp[mask] = 0;
                for (int j = 0; j < N; j++) if (mask & (1 << j)) {
                        dp[mask] += A[k-1][j] * self(mask ^ (1 << j));
                        dp[mask] %= MOD;
                }

                return dp[mask];
        };

        cout << f(mx - 1) << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}