/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75798398
 * Link: https://atcoder.jp/contests/dp/tasks/dp_p
 */

#include <atcoder/modint>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

using mint = atcoder::modint1000000007;

void solution() {
        int N;
        cin >> N;
        vector<vector<int>> adj(N+1);
        for (int _ = 0; _ < N-1; _++) {
                int u, v;
                cin >> u >> v;
                adj[u].emplace_back(v);
                adj[v].emplace_back(u);
        }
        vector<vector<mint>> dp(2, vector<mint> (N+1, 1));
        const auto dfs = [&](this auto &&self, int cur, int parent) -> void {
                test(cur);
                for (auto &nxt : adj[cur]) if (nxt != parent) {
                        self(nxt, cur);
                        dp[0][cur] *= (dp[0][nxt] + dp[1][nxt]);
                        dp[1][cur] *= dp[0][nxt];
                }
        };
        dfs(1, -1);

        cout << (dp[0][1] + dp[1][1]).val() << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
