/*
 * This file was auto-generated by UpCode https://github.com/Srivaths-P/UpCode
 * Submission ID: 75799524
 * Link: https://atcoder.jp/contests/dp/tasks/dp_q
 */

#include <atcoder/segtree>
#include <algorithm>
#include <iostream>
#include <vector>
#ifdef LOCAL
#define test(...) do { std::cerr << "Line(" << __LINE__ << ") [" #__VA_ARGS__ "] =>"; ([](auto&&... args){ ((std::cerr << ' ' << args), ...); }(__VA_ARGS__)); std::cerr << std::endl; } while(0)
#define testv(x) do { std::cerr << "Line(" << __LINE__ << ") " #x " => ["; int _i=0; for (auto& _e : (x)) std::cerr << (_i++ ? ", " : "") << _e; std::cerr << "]" << std::endl; } while(0)
#else
#define test(...) 0
#define testv(...) 0
#endif
#define SQ(x) ((x) * (x))
#define CORDCOMP(x, fx) std::sort(ALL(x)); x.erase(std::unique(ALL(x)), std::end(x)); const auto fx = [&](int val) -> int { return std::lower_bound(ALL(x), val) - std::begin(x); }
#define fst first
#define sec second

using lli = long long int;
using namespace std;

namespace seg {
        lli op(lli a, lli b) { return max(a, b); }
        lli e() { return 0; }
}

void solution() {
        int N;
        cin >> N;
        vector<int> H(N);
        for (auto &h : H) cin >> h;
        vector<int> A(N);
        for (auto &a : A) cin >> a;
        atcoder::segtree<lli, seg::op, seg::e> tr(N+1);
        lli ans = 0;
        for (int i = 0; i < N; i++) {
                lli x = A[i] + tr.prod(0, H[i]);
                ans = max(tr.all_prod(), x);
                tr.set(H[i], x);
        }
        cout << ans << '\n';
}

int main() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
        solution();
        return 0;
}
